### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by blueneogeo** [nativescript-vue/vue-cli-template#10]
More precisely, the option at start to elect (y/n) to have typescript supported in javascript compilation and in the .vue templates.

**Comment by ghost** [comment]
So... is there anybody who got this working with typescript?

**Comment by rigor789** [comment]
see:  https://github.com/nativescript-vue/nativescript-vue/issues/211#issuecomment-385337813

**Comment by ghost** [comment]
Heyyy, thanks!!!
Appreciate it!

**Comment by raffaeler** [comment]
I prefer to wait for typescript support before starting any new project in Vue, which I definitely love more than angular.
I hope to see the template updated soon.

**Comment by ghost** [comment]
@raffaeler I started a project and I must admit, it's been quite painful 😸 
Lucky for me, it's for my own learning pleasure, so apart from the occasional nervous breakdown, it's been quite satisfying.  I've had to let some things go until support is better, but apart from that, interesting.

**Comment by raffaeler** [comment]
@kilroy05 indeed. Also, I did not understand why Vue is a 'different story'.
I expected to use the tns cli and all the familiar things that I used in nativescript with JS and Angular.
This is a kind of breaking change which is definitely not attractive.

**Comment by ghost** [comment]
@raffaeler Yeah, I guess it's debatable on that. I do get the impression this version 1 should be called a release candidate. Doesn't feel like a mature product, yet. But you know, the work they do is still greatly appreciated!

**Comment by raffaeler** [comment]
@kilroy05 I absolutely agree they are doing a great job.
But adoption mostly depends on all the small details ;-)

**Comment by ghost** [comment]
@raffaeler True, true 😸

**Comment by Kosqe** [comment]
For me support for both Typescript and Vue Class Component(https://www.npmjs.com/package/vue-class-component) would make this my preferred mobile framework. 

When I tried to experiment with the combo I fell into so many pitfalls like the TabView not working, random errors like "Calling js method onCreate failed" and "A Frame must be used to navigate to a Page" etc. 

When it worked it was great, but when it didn't, which was often, I felt like screaming and pulling my hair out since there were zero solutions I could find online.

I wouldn't advise anyone to pursue this route until there's official support.

**Comment by jiraiya972** [comment]
> 
> 
> @kilroy05 indeed. Also, I did not understand why Vue is a 'different story'.
> I expected to use the tns cli and all the familiar things that I used in nativescript with JS and Angular.
> This is a kind of breaking change which is definitely not attractive.

you can try again. There has been a big update of the template and now it works with the usual commands `tns...`, sidekick...

https://nativescript-vue.org/en/docs/getting-started/quick-start/

**Comment by htbkoo** [comment]
FWIW, I had added `TypeScript` support to my project bootstrapped with this template in [this commit](https://github.com/htbkoo/hey-hkul-hours-native-ns-vue/commit/7459f1f63e24b283adbdc964aff727455d18e240).
More detailed steps can be found in [my answer at StackOverflow](https://stackoverflow.com/a/53979472/10734272).

Not ideal I guess as there are a few manual steps needed but I guess that's what we have to do at this moment. :-)

Hope it can help and hope that there would be out-of-the-box Type Script support soon!

**Comment by msaelices** [comment]
@htbkoo There is out-of-the-box TS support in this PR: https://github.com/nativescript-vue/vue-cli-template/pull/121

**Comment by raffaeler** [comment]
@msaelices Great.
Does this also align the vue dev-experience to the angular one?
I never had the feeling that vue was a first-class platform in nativescript, and I would really like to see the 'parity'.

**Comment by msaelices** [comment]
Yes, it does :)

My apps are basically TS ones, so the template is now ready for it.
