### ISSUE TITLE
Can't build with new & raw installation

### ISSUE THREAD

**Issue by wendt88** [nativescript-vue/vue-cli-template#102]
### Version
N/A

### Reproduction link
[https://nativescript-vue.org/en/docs/getting-started/quick-start/](https://nativescript-vue.org/en/docs/getting-started/quick-start/)
### Platform and OS info
android   windows 10

### Steps to reproduce
```
$ npm install -g @vue/cli @vue/cli-init
$ vue init nativescript-vue/vue-cli-template <project-name>
$ cd <project-name>
$ npm install
$ tns run android --bundle
```

### What is expected?
Running vue app

### What is actually happening?
`Can't resolve 'nativescript-dev-webpack/style-hot-loader'` during build and on app start:
```
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err: Error calling module function
System.err: Error calling module function
System.err: Error: Cannot find module './App.vue?vue&type=style&index=0&id=45ba5ed4&scoped=true&lang=css&'
System.err: File: "file:///data/data/org.nativescript.application/files/app/bundle.js, line: 253, column: 215
System.err: StackTrace:
System.err:     Frame: function:'webpackMissingModule', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 253, column: 85
System.err:     Frame: function:'./components/App.vue', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 253, column: 226
System.err:     Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
...
```

---
I tried some times with various settings, no one seems to work

**Comment by rigor789** [comment]
That's due to the version of `nativescript-dev-webpack` which uses `^` so it resolves different versions.

Go into `package.json` and change the version to `next` and `npm install` again, this time it should work as expected.

Edit: we just changed this in the repo as well.
