### ISSUE TITLE
JS: Error: Css styling failed: Error: undefined:1:16: missing '{'

### ISSUE THREAD

**Issue by RaisinBread42** [nativescript-vue/vue-cli-template#103]
### Version
N/A

### Reproduction link
[https://github.com/nativescript-vue/vue-cli-template](https://github.com/nativescript-vue/vue-cli-template)
### Platform and OS info
Android / Nativescript 5.0 / Windows 10

### Steps to reproduce
Create a vanilla project using vue-cli-template as explained here https://github.com/nativescript-vue/vue-cli-template

### What is expected?
project builds and runs with no errors

### What is actually happening?
Receiving:  JS: Error: Css styling failed: Error: undefined:1:16: missing '{'.

A snippet of the logs are below:

Project successfully prepared (Android)
...

Refreshing application...
JS: Error: Css styling failed: Error: undefined:1:16: missing '{'
JS: 'HMR Sync...'
JS: Hot Module Replacement Enabled. Waiting for signal.
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(NativeFrame)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(NativePage)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(NativeActionBar)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativepage), ElementNode(nativeactionbar))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(nativescrollview)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(nativeflexboxlayout)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(nativestacklayout)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(nativelabel)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativelabel))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(nativestacklayout)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(nativetextfield)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativetextfield))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(nativestacklayout)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativestacklayout))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativestacklayout))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(nativestacklayout)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(nativetextfield)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativetextfield))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(nativestacklayout)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativestacklayout))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativestacklayout))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> CreateElement(nativebutton)'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativestacklayout), ElementNode(nativebutton))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativeflexboxlayout), ElementNode(nativestacklayout))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativescrollview), ElementNode(nativeflexboxlayout))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativepage), ElementNode(nativescrollview))'
JS: '{NSVue (Vue: 2.5.17 | NSVue: 2.0.0)} -> AppendChild(ElementNode(nativeframe), ElementNode(nativepage))'
Successfully synced application org.nativescript.application on device emulator-5554.

**Comment by rigor789** [comment]
Closing as outdated.
