### ISSUE TITLE
Application not updating in Android until version is changed in package.json

### ISSUE THREAD

**Issue by ramsesmoreno** [nativescript-vue/vue-cli-template#104]
### Version
N/A

### Reproduction link
[https://drive.google.com/file/d/1xeso-3kOevUXcvNJCi5k7-2nJTKxbk4w/view?usp=sharing](https://drive.google.com/file/d/1xeso-3kOevUXcvNJCi5k7-2nJTKxbk4w/view?usp=sharing)
### Platform and OS info
Android 7.0 / 10.13.6. / Nativescript Vue 2.0.0. / tns-android 4.2.0

### Steps to reproduce
Following the steps in QuickStart (https://nativescript-vue.org/en/docs/getting-started/quick-start/) and make a modification in the source files

### What is expected?
The application to be updated in the android emulator just as it does in the iOS emulator

### What is actually happening?
The application is not updated in Android, the applications justs restart but with no changes.

---
Modifying the version in package.json is a workaround like I show in the video.

**Comment by rigor789** [comment]
There is a `Broken Pipe` error in the android logs on the right, that is likely the cause of it failing to sync. 

What is the version of `tns`? (`tns --version`)

**Comment by ramsesmoreno** [comment]
It was 4.1. It is now 4.2.4 and it is working correctly. Thank you.
