### ISSUE TITLE
Using --env.production breaks SegmentedBar

### ISSUE THREAD

**Issue by Reached** [nativescript-vue/vue-cli-template#105]
### Version
Latest version of vue-cli-template and Nativescript Vue (basically bootstrapped a blank project to test this out)

### Reproduction link
[https://github.com/Reached/hockey-test](https://github.com/Reached/hockey-test)
### Platform and OS info
iOS 11-12, MacOS 10.11.4 - simulator and real devices

### Steps to reproduce
`npm install` and
`tns run ios --bundle --env.production`
___
running `tns run ios --bundle` without `--env.production` works as expected

### What is expected?
Segmented bar shows up on the screen

### What is actually happening?
The screen is empty/blank

**Comment by rigor789** [comment]
I noticed the same with FormattedString, but haven't been able to identify the issue...

**Comment by rigor789** [comment]
To fix the issue, make the changes from https://github.com/nativescript-vue/vue-cli-template/commit/c74f1cdd8c716c1155f982ae60396d7a676fab5f in your `webpack.config.js`

**Comment by Reached** [comment]
Thanks @rigor789 and nice find!
