### ISSUE TITLE
js code debug

### ISSUE THREAD

**Issue by wendt88** [nativescript-vue/vue-cli-template#107]
### What problem does this feature solve?
debugging of js code

### What does the proposed API look like?
change `devtool` setting of the `webpack.config.js` from `'none'` to `production ? 'none' : 'eval-source-map'`
so running `tns debug android --bundle` allows you to debug the code in source-map files and not the webpacked bundle-file only

**Comment by rigor789** [comment]
Fixed in `nativescript-dev-webpack` where the `webpack.config.js` is located now (no longer  in this repo)
