### ISSUE TITLE
HMR doesn't work when deleting css

### ISSUE THREAD

**Issue by mathieutu** [nativescript-vue/vue-cli-template#112]
### Platform and OS info
Tested on Android emulator, latest version of all.

### Steps to reproduce
Hi, 
when you're deleting a line of css, in a vue component or in scss file, the deletion is not taken in account.

Example in chronological order:
1. With :
```css
 .title {
    }
```
Title is white.

2. With:
```css
 .title {
        color: blue;
    }
```
Title is blue.

3. With:
```css
 .title {
    }
```
Title stays blue.

### What is expected?
Css should be updated.

### What is actually happening?
Css is not updated.

**Comment by jlooper** [comment]
Hey @mathieutu - Igor has an issue template for a reason, can you please use it? Otherwise it'll be closed and we'll never get anywhere.

**Comment by mathieutu** [comment]
@jlooper It's not really convenient and relevant for some issues, but done. I've wrapped this one with it.

**Comment by rigor789** [comment]
Tracked at https://github.com/nativescript-vue/nativescript-vue/issues/425
