### ISSUE TITLE
HMR fails with log: "HMR is not supported"

### ISSUE THREAD

**Issue by TunaYagci** [nativescript-vue/vue-cli-template#113]
### Version
N/A

### Reproduction link
[https://play.nativescript.org/](https://play.nativescript.org/)
### Platform and OS info
Android 7.1.1 / NativeScript 4.2.4 / MacOS High Sierra

### Steps to reproduce
When I run `tns run android --hmr` it says:  
`The option 'hmr' is not supported. To see command's options, use '$ tns help run'. To see all commands use '$ tns help'.`

### What is expected?
HMR to work.

### What is actually happening?
It outputs error.

**Comment by rigor789** [comment]
`4.2.4` does not support HMR, only the beta versions of the nativescript-cli.
