### ISSUE TITLE
the cmd "vue init nativescript-vue/vue-cli-template" is not working

### ISSUE THREAD

**Issue by ghost** [nativescript-vue/vue-cli-template#115]
I have an error

 vue-cli · Failed to download repo nativescript-vue/vue-cli-template: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxyserverpac proxyserverpac:80

**Comment by ghost** [comment]
I can not create a project using the command "tns create" or "view init nativescript-view / view-cli-template".

I have this error:

"Failed to download repo nativescript-view / view-cli-template: tunneling socket could not be established, cause = getaddrinfo ENOTFOUND proxyserverpac proxyserverpac: 80"

On the other hand with angular, js or typescript the projects are created!

**Comment by yerol** [comment]
It's because it is called "vue-cli-template" not "view-cli-template"

**Comment by yerol** [comment]
Also "nativescript-vue" not "nativescript-view"

**Comment by ghost** [comment]
I speak frensh, I user google translate, it is "nativescript-vue", 
even if I use "tns create" with angular, js or typescript the project is created but not with "vue"
