### ISSUE TITLE
Project fails to build using Xcode 10.2

### ISSUE THREAD

**Issue by toontoet** [nativescript-vue/vue-cli-template#123]
### Version
N/A

### Reproduction link
[https://github.com/naderio/nativescript-socket.io/issues/53](https://github.com/naderio/nativescript-socket.io/issues/53)
### Platform and OS info
Nativescript 5.2

### Steps to reproduce
Create a new project using this template on a system containing Xcode 10.2

vue init nativescript-vue/vue-cli-template testapp

choose Y for using vue-devtools

cd testapp

tns run ios --bundle

### What is expected?
The project runs correct on devices and / or emulator

### What is actually happening?
See output:
```
Preparing project...
Installing pods...
Ignoring curb-0.9.4 because its extensions are not built.  Try: gem pristine curb --version 0.9.4
Ignoring json-2.1.0 because its extensions are not built.  Try: gem pristine json --version 2.1.0
Ignoring unf_ext-0.0.7.4 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.4
Analyzing dependencies
Downloading dependencies
Installing Socket.IO-Client-Swift (11.1.3)
Installing StarscreamSocketIO (8.0.7)
Installing Toaster (2.0.4)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `vueclibug.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 2 dependencies from the Podfile and 3 total pods installed.

[!] Automatically assigning platform `ios` with version `9.0` on target `vueclibug` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Project successfully prepared (iOS)
Building project...
Xcode build...
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Toaster')
error: SWIFT_VERSION '3.1' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Socket.IO-Client-Swift')
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Toaster')
error: SWIFT_VERSION '3.1' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Socket.IO-Client-Swift')
note: Using new build systemnote: Planning buildnote: Constructing build description
** BUILD FAILED **
```

---
The problem comes from an swift version that's not available anymore after updating to XCode 10.2.

The issue is known here: https://github.com/naderio/nativescript-socket.io/issues/53
and here: https://github.com/TobiasHennig/nativescript-toast/pull/36

The cli tempalte should be updated so the newer deps are used.

**Comment by tralves** [comment]
You can fix this issue now by changing `package.json` with:

Replace:

`nativescript-vue-devtools` -> `"nativescript-vue-devtools": "github:anthonny/nativescript-vue-devtools#master",`

`nativescript-toast` -> `"nativescript-toasty": "^1.3.0",`

`nativescript-socket.io` -> `"nativescript-socketio": "^3.2.1",`

This is a temporary solution while the template and `nativescript-vue-devtools` is not fixed, but it works!

**Comment by rigor789** [comment]
Updated `nativescript-vue-devtools` to `1.2.0`.

Make the above changes by @tralves except the first one, as it can use the official package now.
