### ISSUE TITLE
Stuck at project description

### ISSUE THREAD

**Issue by renatomanalili** [nativescript-vue/vue-cli-template#129]
### Version
N/A

### Reproduction link
[https://play.nativescript.org/](https://play.nativescript.org/)
### Platform and OS info
linux

### Steps to reproduce
When creating a new nativescript-vue using vue cli it get stack in project description.

### What is expected?
Proceed with the creation of the project

### What is actually happening?
Stack at project description

---
I think its because I updated the vue cli to 3.8.4.

**Comment by rigor789** [comment]
Closing as there is not enough info to be able to debug this.
If you're still experiencing this issue - open a new issue with detailed logs of the commands you've ran and their outputs.
