### ISSUE TITLE
Error on vue init: `Missing helper: "androidVersionCode"`

### ISSUE THREAD

**Issue by rubybrowncoat** [nativescript-vue/vue-cli-template#13]
```
user ➜ vue init nativescript-vue/vue-cli-template TestVueNativeScript

? Project name test
? Project description A native application built with NativeScript-Vue
? Application name Test
? Unique application identifier net.testudo.test
? Project version 1.0.0
? Author Tester Test <test@test.com>
? License MIT
? Install vue-router? Yes
? Install vuex? Yes
? Color scheme purple
   vue-cli · [template/app/App_Resources/Android/AndroidManifest.xml] Missing helper: "androidVersionCode"
```

I get this error. Nothing else.

Vue CLI version: `2.9.3`

For testing purposes I created a NativeScript JS Hello World project with `tns create` and that works flawlessly, it even compiles and runs on the iOS simulator and on an Android emulator, and `tns doctor` says everything is alright.

I also tried it with `@vue/cli @vue/cli-init` `3.0.0-beta.6` as per instructions at https://nativescript-vue.org/en/docs/getting-started/quick-start/#next-steps but I get the same, identical output. I tried **several** times, with different options on both 2.x and 3.x beta but nothing seems to change the end result.

**Comment by lewebsimple** [comment]
This is an issue with vue-cli being installed globally through yarn and / or npm.. which confuses the `vue` command.

You can test your environment by running `vue init webpack test-webpack` ... it this works you should be ok with `nativescript-vue/vue-cli-template`, if not check your vue-cli installation.
