### ISSUE TITLE
Unable to preview with ios device

### ISSUE THREAD

**Issue by boardmain** [nativescript-vue/vue-cli-template#137]
### Version
N/A

### Reproduction link
[https://github.com/nativescript-vue/vue-cli-template](https://github.com/nativescript-vue/vue-cli-template)
### Platform and OS info
Macos Mojave

### Steps to reproduce
followed the setup guide
when i try to preview with playground i have a fatal error ( Can't find variable SocketManger )

### What is expected?
preview the app in the device

### What is actually happening?
crash

**Comment by boardmain** [comment]
sorry i found a solution in old post
close this

**Comment by boardmain** [comment]
can you add the note in the wizard where devtools ( don't install if you want to try to device )

**Comment by rigor789** [comment]
@boardmain that's a great idea, would you mind opening a PR and adding the note to this page? https://github.com/nativescript-vue/nativescript-vue.org/tree/master/content/docs/en/getting-started/5-vue-devtools.md
