### ISSUE TITLE
style tag not parsed?

### ISSUE THREAD

**Issue by huulbaek** [nativescript-vue/vue-cli-template#15]
It seems to me that the ```<style>``` tag in .vue files are not parsed? Is there any way to make that happen?

For example on my test installation the HelloWorld.vue does not use the styles indicated.

**Comment by lewebsimple** [comment]
You may want to search the #vue channel on the community [Slack](https://developer.telerik.com/wp-login.php?action=slack-invitation) and provide a link to a repository so we can help you find the issue.

**Comment by huulbaek** [comment]
Thank you for your reply @lewebsimple.

I figured it out – I had dynamically loaded components in my router like this:

```
function load (component) {
  return () => System.import(`../components/${component}.vue`)
}
```

When I gave that up, the style tags were loaded and parsed just fine. :)
