### ISSUE TITLE
RFC: Change how externals are handled

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/vue-cli-template#16]
Reference: https://github.com/nativescript-vue/vue-cli-template/issues/12#issuecomment-372790819

My proposal is to mark all `dependencies` as external. This would mean that in order to make a dependecy bundled (not external) it would have to be moved to `devDependencies`.

This approach should work for most people, and we can document it in a *Optimizations* section, where we describe what an external dependency is, how to make something external etc.

I'm open for suggestions, so please leave any feedback here.

**Comment by lewebsimple** [comment]
We could move this to lewebsimple/nativescript-vue-externals

**Comment by rigor789** [comment]
This issue was moved to nativescript-vue/nativescript-vue-externals#2
