### ISSUE TITLE
Cannot import plugins

### ISSUE THREAD

**Issue by qLutCh55** [nativescript-vue/vue-cli-template#20]
Hello there,

I have been trying the past few days trying to import RadSideDrawer from nativescript-pro-ui into a fresh install of this template.

After reading all the docs and current issues with comments, I have still not come across anything to assist in importing external plugins.

Currently in my Home.vue I am importing the Sidedrawer with the following:

 import RadSideDrawer from "nativescript-pro-ui/sidedrawer";
    export default {
        data () {
            return {
                surprise: false,
            };
        },
        components: {
            RadSideDrawer
        }
    };

But webpack still gives this error: 

System.err: Error: com.tns.NativeScriptException: Failed to find module: "sidedrawer\sidedrawer-common", relative to: app/tns_modules/

I am using everything as per the fresh pull of this package. No alterations on any webpack configs. And I did add the package using npm and not tns (according to the docs). Did a npm run clean. But the error still persists.

Any solutions?

**Comment by rigor789** [comment]
Hi, there is a separate page describing how to import NativeScript plugins: https://nativescript-vue.org/en/docs/getting-started/nativescript-plugins/

These elements are not Vue components, so adding it to the `components` option will not work.

**Comment by lewebsimple** [comment]
It is also important to do a `npm run clean` and build / watch again so the installed plugin will get prepared by tns in the dist/ folder.

**Comment by qLutCh55** [comment]
@rigor789 Thanks so much! Finally got it going!

**Comment by qLutCh55** [comment]
So managed to import plugin successfully. But after using it in my template, I am getting the error...

System.err: Error: A Frame must be used to navigate to a Page.
System.err: File: "file:///data/data/org.nativescript.application/files/app/tns_modules/tns-core-modules/ui/frame/frame.js, line: 605, column: 16

Not sure if it webpack throwing the error or that nativescript webpack is not being used?
