### ISSUE TITLE
Impossible to import plugins

### ISSUE THREAD

**Issue by ghost** [nativescript-vue/vue-cli-template#22]
I was trying to make a simple application which plays audio when a button is tapped. However, when I install any plugin via `yarn add plugin-name` or `npm i --save plugin-name`, I simply can't use them. I've tried `nativescript-audio` and `nativescript-sound`, importing them in the vuex store, in `main.js` - and the application either fails at build or crashes at startup.

Sample error log, the line `import { TNSPlayer } from 'nativescript-audio'` is added to `main.js`:
```
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err: Error calling module function
System.err: Error: com.tns.NativeScriptException: Failed to find module: "nativescript-audio\options", relative to: app/tns_modules/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:530)
System.err:     com.tns.Runtime.run(Runtime.java:522)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4825)
System.err:     de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
System.err:     de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:334)
System.err:     android.app.ActivityThread.handleBindApplication(<Xposed>)
System.err:     android.app.ActivityThread.access$1700(ActivityThread.java:156)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:157)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5653)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
System.err:     de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
```

Sample error log 2, in this case the line `import {Sound} from 'nativescript-sound'` is added to `main.js`:
```
ERROR in ./src/main.js
Module not found: Error: Can't resolve 'nativescript-sound' in 'D:\PROGRAMMING\test-ns\src'
 @ ./src/main.js 11:25-54
```

I've also tried to add `tns-core-modules/` to the imports as a prefix, according to the documentation, but it had no effect.

**Comment by lewebsimple** [comment]
Please refer to this section of the README: https://github.com/nativescript-vue/vue-cli-template#using-nativescript-plugins

**Comment by ghost** [comment]
@lewebsimple I have followed the mentioned section, running `npm run clean` after installing plugins via `npm install --save <plugin name>`, and even getting some info at the command-line about the newly added plugins:

```
...snip...
Preparing project...
Successfully prepared plugin nativescript-audio for android.
Successfully prepared plugin nativescript-sound for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin nativescript-vue for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin nativescript-permissions for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (Android)
...snip...
```

It still changes nothing, and I am getting the same errors.

**Comment by ghost** [comment]
Tried to downgrade my `nativescript-vue-externals` to `0.1.1` and running `npm run clean`, but still no luck.

**Comment by Darahat** [comment]
Facing same problem .I also trying on same way but it does not working till now.compiler showing module not found error .Any one can help?

**Comment by ghost** [comment]
Poking @lewebsimple, @tralves, and @rigor789, as the issue still persists.

**Comment by josx** [comment]
any clue on this?

**Comment by ghost** [comment]
I've tried a number of plugins and some seem to work. Some other, however, are impossible to import.

The thing is - a lot of plugins require different undocumented things to work. For example, I was able to get the `nativescript-audio` plugin to work:

```javascript
  import { TNSPlayer } from 'nativescript-audio';
  import * as application from 'tns-core-modules/application';
  let player
  application.on(application.launchEvent, function (args) {
    console.log("App launching...");
    player = new TNSPlayer()
    player.initFromFile({
      audioFile: '~/sounds/beep-01a.mp3', // ~ = app directory
      loop: false
    })
  });
  export default {
    methods: {
      beep() {
        this.surprise = !this.surprise
        player.play()
      }
    }
  };
```

Notice this part of the code:
```javascript
  application.on(application.launchEvent, function (args) {
    console.log("App launching...");
    player = new TNSPlayer()
    player.initFromFile({
      audioFile: '~/sounds/beep-01a.mp3', // ~ = app directory
      loop: false
    })
  });
```

Without it the plugin will fail to play anything. And it isn't even documented - I've found a broken solution with the use of `application.launchEvent` in some god-forgotten issue on github and fixed it in order to work with `nativescript-vue`.

I know the project is just about half a year old, but the lack of documentation, examples and general help is astounding.

**Comment by ghost** [comment]
Closing this because this is somewhat solved.
