### ISSUE TITLE
Path ~/images not working at styles in components .vue

### ISSUE THREAD

**Issue by francisco-gamonal** [nativescript-vue/vue-cli-template#23]
Hello, this is my setup:
- node: v9.8.0
- npm: v5.6.0

My Code
```vue
<template>
  <Page class="page background" actionBarHidden="true">
    
  </Page>
</template>

<script>
export default {  
}
</script>

<style scoped>
.background{
  background-image: url("~/images/background.png");
  background-repeat: no-repeat;
  background-position: center;
  background-size: cover;
}
</style>
```
![Image of Yaktocat](https://image.ibb.co/iFDt4c/template.png)

**Comment by lewebsimple** [comment]
Can you try without the `~` and simply `/images/background.png` ? (also without the `/` in the front)

**Comment by ghost** [comment]
@francisco-gamonal Just remove url() and leave it like that: `background-image: ~/images/background.png`. It should work.

**Comment by francisco-gamonal** [comment]
@dverlik Thanks, it works just like you say.

Please close.
