### ISSUE TITLE
Icon font not working

### ISSUE THREAD

**Issue by Lavhe** [nativescript-vue/vue-cli-template#24]
Even with the simpliest setting.

You can use icon fonts with NativeScript by combining a class with a unicode reference in the view:

**styles.scss**
```
.fa {
  font-family: FontAwesome;
}
```

**view**
`<Label class="fa" text="\uf293"></Label>`

Nothing gets displayed

**Comment by Lavhe** [comment]
SOLUTION FROM slack...

`npm i --save nativescript-fonticon`

Then in your main js file:
```
import { TNSFontIcon, fonticon } from 'nativescript-fonticon';

TNSFontIcon.paths = {
  fa: './FontAwesome.css',
};
TNSFontIcon.loadCss();

Vue.filter('fonticon', fonticon);
``````

Place `FontAwesome.css` in `assets/`, and place `FontAwesome.ttf` in `assets/fonts`.

Create a css class `.fa { font-family: FontAwesome; }`

And finally use like so:
```<Label class="fa" :text="'fa-user' | fonticon" />```

**Comment by Qanah** [comment]
i use fonticon like @Lavhe 

but you can use it by binding
```
<Label class="fa" :text="'\uf293'"></Label>
```

**Comment by SGissubel** [comment]
I tried all of this... and currently, my simulator is just showing wingdings (if you remember what those are).

I installed the package... then what?  Where do you get the css & tff file to put into the app?  I tried just downloading it from the site - and using their files - but that download also does not come with a fontAwesome.tff file. It's not breaking, and it is displaying icons... but again, they are not the correct icons, just a few random image:

This....
`<Label class="fa" :text="'fa-bluetooth' | fonticon" />
	    <Label class="fa" :text="'fa-heart' | fonticon" />
	    <Label class="fa" :text="'fa-user' | fonticon" />`


Is rendering this...
![image](https://user-images.githubusercontent.com/21371158/42797983-e075fd9c-895f-11e8-99f7-3f617b501e1b.png)

**Comment by rigor789** [comment]
I've had this happen with materialdesignicons, the issue for me was that the fonticon plugin expected the char codes to have a lower case `F` in the css file like this:
```
.mdi-access-point-network:before {
    content: "\f003";
}
```
By default the css had uppercase `F`'s. Took me a bit to figure out, but after I replaced them it worked fine for me.

**Comment by jasonadt** [comment]
Thank you very much @rigor789! After many frustrating hours, your suggestion fixed it for me! Who is responsible for getting this fixed for NativeScript-Vue?

**Comment by Qanah** [comment]
@SGissubel 

1.install nativescript-fonticon plugin 
2.copy FontAwesome.ttf to APP_PATH/src/assets/fonts/FontAwesome.ttf
3.copy font-awesome.css to APP_PATH/src/assets/css/font-awesome.css
4.in main.js add this
```
import {TNSFontIcon, fonticon} from 'nativescript-fonticon';

TNSFontIcon.debug = false;
TNSFontIcon.paths = {
    'fa': './css/font-awesome.css',
};
TNSFontIcon.loadCss();

Vue.filter('fonticon', fonticon)
``` 
5. to use
```
<FormattedString >
   <Span :text="tab.icon | fonticon" class="fa" fontSize="24" />
</FormattedString>
```

**Comment by SGissubel** [comment]
@Qanah, so my question is - where do I find the tff & css files?  I don't have them in the nativescript-fonticon node-module. 

![image](https://user-images.githubusercontent.com/21371158/42820807-0815da1c-89a5-11e8-9167-3875b6923595.png)


And if I download the fontawesome for web from the website, I also cannot see/find a tff file.  The only file I saw/used - was in the css folder - all.css file.

**Comment by rigor789** [comment]
@jasonadt it's not a NativeScript-Vue issue, rather an issue with the way `nativescript-fonticon` parses the css - anyone can open a PR, I may do it if I get some time, but in the meantime it's up for grabs. A simple fix would be just adding an `/i` flag to the regex to make it case-insensitive. 

@SGissubel the ttf file should be available for the font of your choice, what font are you trying to use? 

For example, font-awesome when downloaded from their site (I'm not 100% if font-awesome 5 works with NS) there is a folder with the font files, and another folder with the css files:
<img width="458" alt="screen shot 2018-07-17 at 23 29 45" src="https://user-images.githubusercontent.com/879060/42846498-6a48dddc-8a19-11e8-8caa-7fda38807815.png">

That's where you can grab them from.
