### ISSUE TITLE
Import custom font

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/vue-cli-template#26]
_From @hoandang on March 21, 2018 14:22_

nativescript official guide mentions custom fonts will be automatically loaded in /app/fonts but in the nativescript-vue structure doesn't have app fonder but src. Did I generate the structure incorrectly?

I have tried @font-face in scss but it didn't seem to work.

_Copied from original issue: nativescript-vue/nativescript-vue#149_

**Comment by rigor789** [comment]
For this template you should place your fonts inside `src/assets/fonts` and that will be copied to the correct folder (`app/fonts`) in the built application.

**Comment by hoandang** [comment]
I have changed the fonts location and strangely the font still doesn't load up. Is it because of the font's issue?

<img width="527" alt="screen shot 2018-03-22 at 01 36 53" src="https://user-images.githubusercontent.com/1758446/37716249-27091a4a-2d72-11e8-9519-2acc9839f732.png">

**Comment by rigor789** [comment]
It could be a font issue, try playing around with the `font-family`, and try using the name of the font (which I don't know for sure) like `font-family: InfinitiBrandBold, 'Infiniti Brand Bold', 'InfinitiBrand Bold'... etc`

And just to make sure, `npm run clean` and `npm run watch:<platform>` again to make sure the font is actually copied to the device

**Comment by hoandang** [comment]
hmm, the font still doesn't work regardless the name variations. I can tell the font is valid because it works on web with @font-face. May need to try it on native code.

**Comment by hoandang** [comment]
Btw, I am still running on simulator so not sure if its the case?

**Comment by hoandang** [comment]
The issue has been resolved by using the original name of the font, in this case is "Infiniti Brand" without Bold or anything. 

In case if anyone come across this issue, please follow this guide https://docs.nativescript.org/ui/styling#using-fonts.

Cheers for the support.
