### ISSUE TITLE
Using `ScrollView` breaks on ios

### ISSUE THREAD

**Issue by tuqire** [nativescript-vue/vue-cli-template#31]
Hi,

When wrapping the `Home` page in a `ScrollView`, ios renders fine, but then on scroll errors and does nothing. Android is fine.

The same template works fine in the Nativescript Playground.

The error I get when I try to scroll:

```
(Foundation) *** Assertion failure in -[UIGestureGraphEdge initWithLabel:sourceNode:targetNode:directed:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3698.33.6/Source/GestureGraph/UIGestureGraphEdge.m:25
```

Code:

```
<template>
    <Page class="page">
      <ScrollView>
        <StackLayout>
          <TextField class="search" />
          <TextField class="search-2" />
          <TextField class="search" />
          <TextField class="search-2" />
        </StackLayout>
      </ScrollView>
    </Page>
</template>

<style scoped>

.search{
    background-image: url('https://d30y9cdsu7xlg0.cloudfront.net/png/14173-200.png');
    background-position: right center;
    background-repeat: no-repeat;
    height: 640px;
}

.search-2{
    background-image: url('https://d30y9cdsu7xlg0.cloudfront.net/png/14173-200.png');
    background-position: right 20px center;
    background-repeat: no-repeat;
    height: 640px;
}
</style>
```

**Comment by Sultanidze** [comment]
ScrollView works in nativescript-vue/nativescript-vue-template and in project downloaded from playground. But application from this template crashes if ios version greater then 9.3, when you tap or scroll the ScrollView.

Now we need to rewrite the whole application because of this issue. It is critical issue!

**Comment by tuqire** [comment]
We fixed this by adding the following to the parent page, or could be used as a mixin:

```
export default {
  data () {
    return { ready: false }
  },
  mounted () {
    this.ready = true
  }
}
```

And then

```
<FlexboxLayout flexDirection="column" class="page" v-if="ready">
```

Not ideal, but did the job.

**Comment by Sultanidze** [comment]
Thank you. But it is little buggy workaround, when you return to this page it blinks (becomes visible after some time). I think issue is not closed. We remake our app now, and use simple nativescript-vue-template, to avoid possible errors in future.

**Comment by Sultanidze** [comment]
It seems that vue-router causes the problem on a first screen of the application.
