### ISSUE TITLE
background image css with local url does not work as expected

### ISSUE THREAD

**Issue by tuqire** [nativescript-vue/vue-cli-template#32]
Hi,

When giving an element a background image stored locally, valid CSS syntax seems to not work. 

What works:

`background-image: ~/images/search.png`;

What doesn't work, but imo should:

`background-image: url('~/images/search.png')`;

**Comment by sudhanshu-15** [comment]
Facing similar issue, also not able to get image hosted on server.

**Comment by 7ammer** [comment]
Hello, so the issue (at least for me) is with cssnano. It is striping out the quotes around the url.
If you disable the below in the `webpack.config.js` file then images will work again. 

```
      // new OptimizeCssAssetsPlugin({
      //   cssProcessor: require('cssnano'),
      //   cssProcessorOptions: {discardComments: {removeAll: true}},
      //   canPrint: false,
      // }),
```

cssnano is also messing with the colours causing errors seen in this issue as well:
https://github.com/nativescript-vue/nativescript-vue/issues/212

Could we perhaps use an alternative that is less ruthless in its optimisations?

**Comment by jpldev** [comment]
Same issue.

I tried

  .layoutBackgroundImageFromFolder{
      background-image: "~/images/grass.jpg";
      background-repeat: no-repeat;
      height: 100%;
      margin: 100%;
  }

  .layoutBackgroundImageURL{
    background-image: url("http://www.tallahasseeultimate.com/Images/grass-background.jpg");
    background-repeat: no-repeat;
    height: 100%;
    width: 100%;
  }


But neither works

**Comment by rigor789** [comment]
@jpldev 

Try the second one without the `url` part? 

I think this is an issue mixed with css nano and webpack rewriting paths because I think paths starting with ~ are treated as "modules". I'm not sure if this is disabled in the template...

**Comment by microwavesafe** [comment]
I'm suffering the same problem, before the fix @7ammer suggested, I tried
```
background-image: url("~/images/image.png");
background-image: "~/images/image.png";
background-image: "~/images/image";
```
All gave the same error
```
JS: Error in downloadBitmap - java.net.MalformedURLException: no protocol: "~/images/image.png"
```
Commenting out the ```OptimizeCssAssetsPlugin``` from webpack and using
```
background-image: url("~/images/image.png");
```
loaded the background image.

**Comment by jpldev** [comment]
@rigor789 

I tried 

  .layoutBackgroundImageURL{
    background-image: "http://www.tallahasseeultimate.com/Images/grass-background.jpg";
    background-repeat: no-repeat;
    height: 100%;
    width: 100%;
  }

but doesn't works

it's rare because in the playground this code works

.layoutBackgroundImageURL{
    background-image: url("http://www.tallahasseeultimate.com/Images/grass-background.jpg");
    background-repeat: no-repeat;
    height: 100%;
    width: 100%;
    
}

I'll keep trying commenting out the OptimizeCssAssetsPlugin like @microwavesafe and @7ammer

**Comment by jpldev** [comment]
It works commenting out the OptimizeCssAssetsPlugin 

  .layoutBackgroundImageFromFolder{
      background-image: url('~/images/newgrass.jpeg');
      background-repeat: no-repeat;
      height: 100%;
      height: 100%;
  }

Thanks to all
