### ISSUE TITLE
Build for production / release?

### ISSUE THREAD

**Issue by huulbaek** [nativescript-vue/vue-cli-template#37]
It seems to me that building for production like in the readme:

```npm run build:android```

creates <applicationName>-debug.apk – so it's still the debug distribution created?

I'm trying to test the initial load time of an app on Android which appears slow but should be faster for a release – also because Android snapshot should be enabled.

Am i missing something?

I guess what I'm concerned about is that I have two functional identical apps – one built with nativescript-vue and this template, and one built with Cordova and the Quasar Framework.

The Cordova one is much faster at initial startup and also faster when navigating router components and I guess I was somewhat expecting the opposite.

**Comment by psnehanshu** [comment]
I am also facing this issue, nobody seems to care.

**Comment by tralves** [comment]
We do care ❤️, it is just hard to get everywhere.

After running `npm run build:android`, cd into `build` and then follow the steps in https://docs.nativescript.org/publishing/publishing-android-apps. 

E.g.

```
cd dist
tns build android --release --key-store-path my-release-key.jks  --key-store-password 123456 --key-store-alias my-alias --key-store-alias-password 123456
```

The release apk should be in the directory `dist/platforms/android/app/build/outputs/apk/release`.

**Comment by psnehanshu** [comment]
Will these steps remove screen like this? 
Ignore the error, I just don't want my users to see this screen even when there is an error.

![screenshot_20180602-202932](https://user-images.githubusercontent.com/9392350/40879740-20e6162a-66c2-11e8-8a8d-e920d7c7f17f.png)

**Comment by eladcandroid** [comment]
@tralves Thanks! 
I think you should add it to vue nativescript docs

**Comment by tralves** [comment]
@eladcandroid ah! I was going to then I forgot. Thank you for remembering me 👍
