### ISSUE TITLE
tns doctor shows errors

### ISSUE THREAD

**Issue by zollipaul** [nativescript-vue/vue-cli-template#39]
I am able to run the project on ios, but "tns doctor" in the terminal shows errors:

✔ Getting environment information

✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
No issues were detected.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 4.0.0 version and is up to date.
✖ Component tns-core-modules is not installed.
✖ Component tns-android is not installed.
✖ Component tns-ios is not installed.

What do I have to do here? "tns platform add ..."? Why does it work anyways (e.g. with npm run watch:ios)?

**Comment by rigoparis** [comment]
Hey @zollipaul,

Up to what I've experimented and done with this template:

tns-platform gets installed once you build the app (that's why it works without you installing it).

Regarding the tns-core-modules: make sure you have the package added in the package.json on your root dir.

Hope this helps you n.n

**Comment by clintrobinson** [comment]
I have this exact same issue and I can't resolve. The project runs with npm run watch, but I can't get tns install or anything like that to work. My tns doctor has the exact same output as above.

**Comment by saleh-old** [comment]
I'm experiencing the exact same issue.

**Comment by rigor789** [comment]
This is perfectly normal, this template is not a tns template (hence the name vue-cli-template). The tns compatible folder is built when you run `npm run watch` inside the dist folder, based on the template folder. If you run `tns doctor`  inside the `dist` folder you should see that there are no issues.

**Comment by saleh-old** [comment]
Thanks for your response. It would be nice to mention this in the docs as well to prevent future confusions.
