### ISSUE TITLE
Vue-Router beforeRouteEnter

### ISSUE THREAD

**Issue by rigoparis** [nativescript-vue/vue-cli-template#41]
Hey guys!

I've been still working on tests and app building for this template and I do understand that Vue-Router is still experimental and it might actually be the issue but here it goes:

My situation is like this: 
I have a SideDrawer that on it's mainContent View is a router-view so that I can just use the sideDrawer as parent for everyone and grab all the routes and build a menu based on the routes of the app.
```
<router-view ~mainContent/>
```

But when in the child component I try to use a `beforeRouteEnter`, the application crashes with the following error:
```
Calling js method onCreate failed 
Error: A Frame must be used to navigate to a Page.
```
And if I change the `beforeRouteEnter` to let's say a `created()` the application doesn't crash and data is retrieved fine but when I try to navigate back to said child I get the following error:
```
JS: [Vue warn]: Error in directive view inserted hook: "Error: View not added to this instance. View: ListView(37) CurrentParent: undefined ExpectedParent: t(24)"
JS: 
JS: found in
JS: 
JS: ---> <SideDrawer> at src/sideDrawer.vue
JS: [Vue warn]: Error in nextTick: "Error: View not added to this instance. View: ListView(37) CurrentParent: undefined ExpectedParent: t(24)"
```

Please let me know if I made myself clear enough with the explanation (I know it might be hard xD) but if you need sample code I am more than willing to share.

Thanks in advance for any help provided!

**Comment by rigor789** [comment]
I would wrap the <router-view> in a GridLayout (the fastest afaik), and add the `~mainContent` directive to that. Dynamically changing components might cause issues with it.

**Comment by rigoparis** [comment]
Hey @rigor789 

Sorry for answering until now! Unfortunately your fix didn't fix the issue but I went ahead and took a different approach which I will explain and hopefully clears anyone else with this issue

Instead of making the SideDrawer a parent component I went ahead and made it with slots and added it to the system as a component. This allowed me to have children views that didn't had to have the SD and it fixed the error I was getting about `View not added to this instance.`. 

My SD:

```
<template>
  <GridLayout rows="*" >
    <RadSideDrawer ref="drawer" @drawerOpened="toggleAbierto"
                   @drawerClosed="toggleAbierto">
      <StackLayout ~drawerContent backgroundColor="white">
        <StackLayout height="180" class="header">
          <Image src="~/images/NativeScript-Vue.png" class="header-image"/>
          <Label :text="usuario.nombre" />
          <Label :text="usuario.correo" />
        </StackLayout>
        <ScrollView height="280">
          <ListView for="ruta in rutas" @itemTap="enrutar" separatorColor="transparent">
            <v-template>
              <StackLayout orientation="horizontal">
                <Label class="fa" :text="`${ruta.meta.icono}` | fonticon"
                       padding="10"
                       fontSize="18"/>
                <Label :text="ruta.meta.title" padding="10"/>
              </StackLayout>
            </v-template>
          </ListView>
        </ScrollView>
        <Label text="Log out" color="gray" padding="10"
               style="horizontal-align: center; bottom: 0;" @tap="cerrarSesion"/>
      </StackLayout>
      <GridLayout ~mainContent>
        <slot/>
      </GridLayout>
    </RadSideDrawer>
  </GridLayout>
</template>
```

Regarding the other problem with `beforeRouteEnter()`: I wasn't able to make it work at all, the function does execute but it seems the `next()` callback is not being executed or not being resolved properly. I went ahead and fixed this by using the `beforeCreate()` hook from the Vue instance instead.

Hope this sheds some light on people that had the same routing problem with a sidedrawer as I had. I'm going to continue testing `beforeRouteEnter()`... but until something positive comes out I recommend using `beforeCreate()`
