### ISSUE TITLE
fully remove back Button from ActionBar (clearHistory) 

### ISSUE THREAD

**Issue by Qanah** [nativescript-vue/vue-cli-template#42]
i have login view after login push the router to tab view i don't need the back Button,
also win i press logout i push the router to login i have navigation Bar with back button refer to settings view 

look for this issue in nativescript-angular
[https://github.com/NativeScript/nativescript-angular/issues/284](https://github.com/NativeScript/nativescript-angular/issues/284)

now i just make the NavigationButton visibility="collapse" but this is not good approach

**Comment by vitouchhay1** [comment]
i have the same issue .

**Comment by rigoparis** [comment]
Hey @Qanah and @vitouchhay1 

Are these views each with their own respective `<Page>`, `<ActionBar>` and other elements?

**Comment by Qanah** [comment]
@rigoparis i am not understand what you need to tel me, but yes each component has own ```<Page>``` and ```<ActionBar>```

**Comment by kuamatzin** [comment]
Hi! @Qanah i have the same problem, did you find a solution?

**Comment by mayconpaivac** [comment]
I also have the same problem.
By signing in, I redirect to home. Pressing the back button again displays the login screen.

**Comment by vitouchhay1** [comment]
I found this not use vue-router
this.$navigateTo(page, {
          animated: true,
          transition: {},
          transitionIOS: {},
          transitionAndroid: {
              name: 'fade',
              duration: 200,
              curve: 'ease'
          },
          clearHistory: true
        });

**Comment by mayconpaivac** [comment]
@vitouchhay1, i was using the vue-router (I find it more elegant and organized), but I think I use it as you do.
Thank you.
