### ISSUE TITLE
“Searching for devices…” when I try to run a new nativescript-vue project?

### ISSUE THREAD

**Issue by huyaxiong** [nativescript-vue/vue-cli-template#43]
![xnip2018-04-114_11-08-58](https://user-images.githubusercontent.com/6245250/39165179-a8ea5bde-47b5-11e8-8fcb-02cf34898fb5.jpg)

I create a nativescript-vue project which following the official start guide here

But when I try to start and preview it on the browser...Nothing I can get from the terminal except "Searching for devices..."

I'm new to it, can someone give me some help on it?

**Comment by huyaxiong** [comment]
![image](https://user-images.githubusercontent.com/6245250/39165203-cf4685d2-47b5-11e8-86fe-4c0281474d4e.png)

when I run `tns doctor`

**Comment by rigoparis** [comment]
Hey @huyaxiong!

Make sure your computer is recognizing the phone as a valid development device

I use `adb devices` for that on Linux

If the device is not listed there, it's not recognized by the computer as a valid device

**Comment by huyaxiong** [comment]
I opened x-code and installed some stuff and then it worked.
