### ISSUE TITLE
ERROR in app.ios.js from UglifyJs

### ISSUE THREAD

**Issue by Qanah** [nativescript-vue/vue-cli-template#45]
install ```nativescript-localstorage```
then ```require("nativescript-localstorage");``` in main.js

then watch:ios i got something like this
```
ERROR in app.ios.js from UglifyJs
Unexpected token: name (localStorageData) [app.ios.js:17875,8]
```

after some search i found the UglifyJs work only on es5 i don't  know if this is the problem
but if this error have side effect please help me to find solution i don't have good experience in webpack

**Comment by Qanah** [comment]
Please any one can help wen i commit the exclude node_modules from webpack rules the error disappear that mean i need to convert all the src and his dependence to es5 and then the UglifyJs
will work without any error
```
//exclude: /(node_modules)/,
```

but any one can help me if there is any issue in my work because in main.js you need to use nativescript-plugins and that plugins is under  node_modules directory then the babel-loader will add it without transform it to es5

**Comment by damiani** [comment]
There's are a couple of threads (https://github.com/webpack/webpack/issues/2972 and https://github.com/joeeames/WebpackFundamentalsCourse/issues/3#issuecomment-344413628) which discuss this issue, but one solution that worked for me in a similar situation is in [this comment](https://github.com/joeeames/WebpackFundamentalsCourse/issues/3#issuecomment-3444136280) ... basically, updating the Uglify plugin that Webpack uses by default.
