### ISSUE TITLE
successful ios build but no ipa file?

### ISSUE THREAD

**Issue by toddkao** [nativescript-vue/vue-cli-template#46]
can't seem to build an ipa file or i don't know where it was built,
i'm expecting it to be in dist/platforms/ios/build/device folder but that folder does not exist 

i'm running this command: npm run build:ios
i tried resetting deriveddata folder
i tried setting DEVELOPMENT_TEAM = TEAM_ID in build.xcconfig

log is as follows:
Xcode build...
=== BUILD TARGET dist OF PROJECT dist WITH CONFIGURATION Debug ===
while processing /Users/lk/VueNS/dist/platforms/ios/internal/TKLiveSync/TKLiveSync(TKLiveSync.o):
warning: /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/28BJBFDGVGZZ3/UIKit-1V5UHAPTOD24G.pcm: No such file or directorywhile processing /Users/lk/VueNS/dist/platforms/ios/internal/TKLiveSync/TKLiveSync(TKLiveSync.o):
warning: /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2DKXPQ92SAISO/UIKit-1V5UHAPTOD24G.pcm: No such file or directory
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will bedegraded due to incomplete debug information.
while processing /Users/lk/VueNS/dist/platforms/ios/internal/TKLiveSync/TKLiveSync(TKLiveSync.o):

warning: /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2DKXPQ92SAISO/Darwin-38I6DLZ5IH61J.pcm: No such file or directory
note: Linking a static library that was built with -gmodules, but the module cache was not found.  Redistributable static libraries should never be built with module debugging enabled.  The debug experience will bedegraded due to incomplete debug information.
while processing /Users/lk/VueNS/dist/platforms/ios/internal/TKLiveSync/TKLiveSync(TKLiveSync.o):
warning: /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2DKXPQ92SAISO/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/lk/VueNS/dist/platforms/ios/internal/TKLiveSync/TKLiveSync(TKLiveSync.o):
warning: /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/28BJBFDGVGZZ3/Darwin-38I6DLZ5IH61J.pcm: No such file or directorywhile processing /Users/lk/VueNS/dist/platforms/ios/internal/TKLiveSync/TKLiveSync(TKLiveSync.o):
warning: /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2DKXPQ92SAISO/Dispatch-2LX9MWM6UEPQW.pcm: No such file or directory
while processing /Users/lk/VueNS/dist/platforms/ios/internal/TKLiveSync/TKLiveSync(TKLiveSync.o):
warning: /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/2DKXPQ92SAISO/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory

while processing /Users/lk/VueNS/dist/platforms/ios/internal/TKLiveSync/TKLiveSync(TKLiveSync.o):
warning: /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/28BJBFDGVGZZ3/Foundation-3DFYNEBRQSXST.pcm: No such file or directory
while processing /Users/lk/VueNS/dist/platforms/ios/internal/TKLiveSync/TKLiveSync(TKLiveSync.o):
warning: /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/28BJBFDGVGZZ3/Dispatch-2LX9MWM6UEPQW.pcm: No such file or directory
while processing /Users/lk/VueNS/dist/platforms/ios/internal/TKLiveSync/TKLiveSync(TKLiveSync.o):
warning: /Users/nsbuilduser/Library/Developer/Xcode/DerivedData/ModuleCache/28BJBFDGVGZZ3/ObjectiveC-1RQA2RIXJIE19.pcm: No such file or directory
Project successfully built.

**Comment by rigor789** [comment]
I'm not sure where the file is supposed to be, but what I've done in the past with great success was to open up the workspace in xcode, and archive from there. This allowed me to upload to the store easily, and all certificates were managed by xcode, I just had to select a few things.

**Comment by evanfuture** [comment]
I'd just comment that this is not really closed.  In systems where the build is automated (and the delivery as well), opening the file manually is not good enough.

I'm looking into this today, I will write back if I make progress.

**Comment by evanfuture** [comment]
Ok, so I ran the following: `cd dist && tns build ios --release --forDevice` and that generated an ipa file inside `dist/platforms/ios/build/device/`

The main issue I see here (maybe not an issue) is that the project is referred to as "dist", eg, the file is named "dist.ipa".

I also needed to append `--provision "XXX"` to the command so it was ready to upload, but others may not need that step.
