### ISSUE TITLE
Fail Npm Install

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/vue-cli-template#50]
_From @jpldev on May 3, 2018 4:17_

Hellow! I follow the quick start https://nativescript-vue.org/en/docs/getting-started/quick-start/
but I couldn't start the app. When I do npm install it fails. 
Any help?

Thanks!

Juans-MacBook-Pro:sportsApp jpldev$ sudo npm install

> fsevents@1.2.3 install /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/fsevents
> node install

[fsevents] Success: "/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> node-sass@4.9.0 install /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-sass
> node scripts/install.js

Unable to save binary /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-sass/vendor/darwin-x64-57 : { Error: EACCES: permission denied,mkdir '/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-sass/vendor' }

> uglifyjs-webpack-plugin@0.4.6 postinstall /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

> node-sass@4.9.0 postinstall /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-sass
> node scripts/build.js

Building: /usr/local/bin/node /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | darwin | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/which/which.js:13:12)
gyp verb `which` failed     at F (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/which/which.js:68:19)
gyp verb `which` failed     at E (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/which/which.js:80:29)
gyp verb `which` failed     at /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/which/which.js:89:16
gyp verb `which` failed     at /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/isexe/index.js:42:5
gyp verb `which` failed     at /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/isexe/mode.js:8:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/which/which.js:13:12)\n    at F (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/which/which.js:68:19)\n    at E (/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/which/which.js:80:29)\n    at /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/which/which.js:89:16\n at /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/isexe/index.js:42:5\n    at /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/isexe/mode.js:8:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python /usr/bin/python
gyp verb check python version `/usr/bin/python -c "import platform; print(platform.python_version());"` returned: "2.7.10\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.4
gyp verb command install [ '8.9.4' ]
gyp verb install input version string "8.9.4"
gyp verb install installing version: 8.9.4
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.4
gyp verb build dir attempting to create "build" dir: /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-sass/build
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-sass/build'
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/usr/local/bin/node" "/Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/jpldev/PersonalProjects/SportsApp/sportsApp/node_modules/node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sports-app@1.0.0 No repository field.
npm WARN sports-app@1.0.0 license should be a valid SPDX license expression

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jpldev/.npm/_logs/2018-05-03T04_12_17_398Z-debug.log

_Copied from original issue: nativescript-vue/nativescript-vue-webpack-template#6_

**Comment by rigor789** [comment]
Any reason that you are running it with `sudo`? That should not be necessary at all.

**Comment by jpldev** [comment]
I try with sudo because it says "coudn't write on", or something like permission. But first I tried without sudo and fails too.

**Comment by rigor789** [comment]
What are the folder permissions on the project folder? Because if you used `sudo` to create the project, you may have no permission to write inside the project directory.

**Comment by christla** [comment]
same issue here
