### ISSUE TITLE
npm run build:android 'throws an error'

### ISSUE THREAD

**Issue by rigor789** [nativescript-vue/vue-cli-template#52]
_From @nyitithania on April 27, 2018 4:41_

Am trying to do a production build for internal testing, put the APK in the play store for easy sharing. tried to do an npm clean and npm install later and still no changes. 

npm run watch:android works fine but i get an error in between 

---------------------------- npm run watch:android OUTPUT STARTS HERE ------------------------------------
> agent@1.0.0 watch:android /home/antony/MyApps/Mobile/AdminApp
> npm run watch -- --env.android

> agent@1.0.0 watch /home/antony/MyApps/Mobile/AdminApp
> webpack --watch --env.tnsAction run "--env.android"

info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...
npm WARN agent@ No repository field.
npm WARN agent@ license should be a valid SPDX license expression

info: Bundling application for android...

Webpack is watching the files…

Executing post-build scripts

ERROR in ./node_modules/got/index.js
Module not found: Error: Can't resolve 'electron' in '/home/antony/MyApps/Mobile/AdminApp/node_modules/got'
 @ ./node_modules/got/index.js 91:20-39
 @ ./node_modules/vue-resource/dist/vue-resource.esm.js
 @ ./src/store/index.js
 @ ./src/main.js

ERROR in app.android.js from UglifyJs
Invalid assignment [app.android.js:18486,40]
info: Running NativeScript application...
Searching for devices...
Preparing project...
Project successfully prepared (Android)
Refreshing application...
Successfully synced application org.nativescript.application on device emulator-5554.

------------------------- npm run build:android  OUTPUT STARTS HERE ---------------------------------------
^Cantony@cctv-t:~/MyApps/Mobile/AdminApp$ npm run build:android

> agent@1.0.0 build:android /home/antony/MyApps/Mobile/AdminApp
> npm run build -- --env.android

> agent@1.0.0 build /home/antony/MyApps/Mobile/AdminApp
> webpack --env.tnsAction build "--env.android"

info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...
npm WARN agent@ No repository field.
npm WARN agent@ license should be a valid SPDX license expression

info: Bundling application for android...
Executing post-build scripts

ERROR in ./node_modules/got/index.js
Module not found: Error: Can't resolve 'electron' in '/home/antony/MyApps/Mobile/AdminApp/node_modules/got'
 @ ./node_modules/got/index.js 91:20-39
 @ ./node_modules/vue-resource/dist/vue-resource.esm.js
 @ ./src/store/index.js
 @ ./src/main.js

ERROR in app.android.js from UglifyJs
Invalid assignment [app.android.js:18486,40]
info: Building NativeScript application...
Preparing project...
Project successfully prepared (android)
Building project...
Gradle build...
	 + applying user-defined configuration from /home/antony/MyApps/Mobile/AdminApp/dist/app/App_Resources/Android/app.gradle
	 + add include.gradle from /home/antony/MyApps/Mobile/AdminApp/dist/node_modules/nativescript-fontawesome/platforms/android/include.gradle
	 + applying plugin configuration from /home/antony/MyApps/Mobile/AdminApp/dist/platforms/android/app/build/configurations/nativescript-fontawesome/include.gradle
	 + adding nativescript runtime package dependency: nativescript-optimized
	 + adding aar plugin dependency: /home/antony/MyApps/Mobile/AdminApp/dist/node_modules/nativescript-ui-sidedrawer/platforms/android/TNSSideDrawer-release.aar
	 + adding aar plugin dependency: /home/antony/MyApps/Mobile/AdminApp/dist/node_modules/nativescript-ui-core/platforms/android/TNSCore-release.aar
	 + adding aar plugin dependency: /home/antony/MyApps/Mobile/AdminApp/dist/node_modules/tns-core-modules-widgets/platforms/android/widgets-release.aar
false
Running full build
Project successfully built.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! agent@1.0.0 build: `webpack --env.tnsAction build "--env.android"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the agent@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/antony/.npm/_logs/2018-04-27T04_13_39_571Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! agent@1.0.0 build:android: `npm run build -- --env.android`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the agent@1.0.0 build:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/antony/.npm/_logs/2018-04-27T04_13_39_704Z-debug.log 

---------------------------------------------- PACKAGE.JSON --------------------------------------------------------

{
  "name": "agent",
  "version": "1.0.0",
  "description": "My description",
  "author": "my name",
  "license": "Creative Commons (CC)",
  "scripts": {
    "build": "webpack --env.tnsAction build",
    "build:android": "npm run build -- --env.android",
    "build:ios": "npm run build -- --env.ios",
    "debug": "webpack --watch --env.tnsAction debug",
    "debug:android": "npm run debug -- --env.android",
    "debug:ios": "npm run debug -- --env.ios",
    "watch": "webpack --watch --env.tnsAction run",
    "watch:android": "npm run watch -- --env.android",
    "watch:ios": "npm run watch -- --env.ios",
    "clean": "rimraf dist"
  },
  "dependencies": {
    "nativescript-exit": "^1.0.1",
    "nativescript-fonticon": "^1.1.1",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-sidedrawer": "^4.0.0",
    "nativescript-vue": "^1.3.1",
    "tns-core-modules": "~3.4.1",
    "vue-resource": "^1.5.0",
    "vue-router": "^3.0.1",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^3.0.2",
    "fs-extra": "^5.0.0",
    "nativescript-vue-externals": "^0.1.2",
    "nativescript-vue-loader": "^0.1.5",
    "nativescript-vue-target": "^0.1.0",
    "nativescript-vue-template-compiler": "^1.3.1",
    "node-sass": "^4.7.2",
    "ns-vue-loader": "^0.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "rimraf": "^2.6.2",
    "sass-loader": "^6.0.7",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^3.11.0",
    "webpack-synchronizable-shell-plugin": "0.0.7",
    "winston-color": "^1.0.0"
  }
}

_Copied from original issue: nativescript-vue/nativescript-vue#209_

**Comment by NicoDos** [comment]
Hello,

Also running the issue, here is the process (from the very start):
`
sudo npm install -g vue-cli
vue init nativescript-vue/vue-cli-template hello-vue
cd hello-vue
npm install
npm run build:ios
`

And the output:
`
> hello-vue@1.0.0 debug:android /Users/nicolassandron/Repositories/hello-vue
> npm run debug -- --env.android


> hello-vue@1.0.0 debug /Users/nicolassandron/Repositories/hello-vue
> webpack --watch --env.tnsAction debug "--env.android"

info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...
npm WARN hello-vue@ No repository field.

info: Bundling application for android...

Webpack is watching the files…

Executing post-build scripts
info: Debugging NativeScript application...
error: uncaughtException: 127 date=Wed May 16 2018 17:23:29 GMT+0200 (CEST), pid=17623, uid=501, gid=20, cwd=~/Repositories/hello-vue, execPath=/usr/local/bin/node, version=v8.10.0, argv=[/usr/local/bin/node, ~/Repositories/hello-vue/node_modules/.bin/webpack, --watch, --env.tnsAction, debug, --env.android], rss=178946048, heapTotal=141574144, heapUsed=95822736, external=768502, loadavg=[2.36376953125, 2.29443359375, 2.10595703125], uptime=688330, trace=[], stack=undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-vue@1.0.0 debug: `webpack --watch --env.tnsAction debug "--env.android"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello-vue@1.0.0 debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-05-16T15_23_29_117Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello-vue@1.0.0 debug:android: `npm run debug -- --env.android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello-vue@1.0.0 debug:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-05-16T15_23_29_326Z-debug.log`

Node version: v8.10.0
NPM version: 6.0.1

**Comment by xeroxstar** [comment]
It will not crash your app, this error you are getting only because of the node issue. Most of the times you will get this bug when you build or watch your app, the node crashes and stop working, but it will not affect the performance of your app. I am getting the same output after the node crash,  but my app is working.

**Comment by nyitithania** [comment]
i eventually found out what was wrong, i was requred to sign my apk so that i can get a release version i also used the tns build android command inside the dist folder because i was not able to get the nmp comand to work. Thanks guys for your feedback

tns build android --compileSdk 22 --key-store-path /home/nyitithania/MyApps/Mobile/keystone.jks --key-store-password mypassword --key-store-alias agentapp --key-store-alias-password mypassword --release

**Comment by xeroxstar** [comment]
@nyitithania thx for info, i will try it too :)
