### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by ZeroTworu** [nativescript-vue/vue-cli-template#54]
Can i use pretty debug by webshtorm?
After i run **npm run debug:<platform>**  i can access  to chrome devtools from chrome, but compiled webpack looks ugly.
![default](https://user-images.githubusercontent.com/17995677/40091388-b524eb68-58d0-11e8-8765-baacfd97f8e4.png)
If i try to access devtools from webshtorm from where:
![default](https://user-images.githubusercontent.com/17995677/40091429-11d54862-58d1-11e8-9f43-fe6f7d4bd4bf.png)

I get this error:
![default](https://user-images.githubusercontent.com/17995677/40091413-f0cf4244-58d0-11e8-82b0-079e2554504b.png)

**Comment by kylawamg** [comment]
no updates?? :(
