### ISSUE TITLE
Error:error: uncaughtException: Command failed: node launch.js run

### ISSUE THREAD

**Issue by NightravenJames** [nativescript-vue/vue-cli-template#55]
I get this error after running `npm run watch:android`

error: uncaughtException: Command failed: node launch.js run android
 date=Wed May 16 2018 12:10:10 GMT+0300 (E. Africa Standard Time), pid=8940, uid=null, gid=null, cwd=C:\Users\dan\Desktop\vue-app,
execPath=C:\Program Files\nodejs\node.exe, version=v8.11.2, argv=[C:\Program Files\nodejs\node.exe, C:\Users\dan\Desktop\vue-app\node_modules\webpack\bin\webpack.js, --watch, --env.tnsAction, run, --env.android], rss=181923840, heapTotal=155947008, heapUsed=106385472, external=1116597, loadavg=[0, 0, 0], uptime=162971.1631496, trace=[column=12, file=child_process.js, function=ChildProcess.exithandler, line=275, method=exithandler, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=ChildProcess.emit, line=214, method=emit, native=false, column=16, file=internal/child_process.js, function=maybeClose, line=925, method=null, native=false, column=11, file=internal/child_process.js, function=Socket.stream.socket.on, line=346, method=on, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false,
column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=12, file=net.js, function=Pipe._handle.close [as _onclose], line=557, method=close [as _onclose], native=false], stack=[Error: Command failed: node launch.js run android, ,     at ChildProcess.exithandler (child_process.js:275:12),     at emitTwo (events.js:126:13),     at ChildProcess.emit (events.js:214:7),     at maybeClose (internal/child_process.js:925:16),     at Socket.stream.socket.on (internal/child_process.js:346:11),
    at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at Pipe._handle.close [as _onclose] (net.js:557:12)]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-app@0.0.0 watch: `webpack --watch --env.tnsAction run "--env.android"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-app@0.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dan\AppData\Roaming\npm-cache\_logs\2018-05-16T09_10_10_316Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-app@0.0.0 watch:android: `npm run watch -- --env.android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-app@0.0.0 watch:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dan\AppData\Roaming\npm-cache\_logs\2018-05-16T09_10_10_468Z-debug.log

**Comment by toyah** [comment]
Same here, on arch linux:
```
npm run build:android

> test-vue@1.0.0 build:android /home/toyah/workspace/test-vue
> npm run build -- --env.android


> test-vue@1.0.0 build /home/toyah/workspace/test-vue
> webpack --env.tnsAction build "--env.android"

info: Copying NativeScript plugins to template dependencies...
info: Preparing NativeScript application from template...
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test-vue@ No repository field.

info: Bundling application for android...
(node:12632) ExperimentalWarning: The fs.promises API is experimental
Executing post-build scripts
info: Building NativeScript application...
error: uncaughtException: 127 date=Thu May 24 2018 11:42:20 GMT+0300 (EAT), pid=12632, uid=1000, gid=100, cwd=/home/toyah/workspace/test-vue, execPath=/usr/bin/node, version=v10.1.0, argv=[/usr/bin/node, /home/toyah/workspace/test-vue/node_modules/.bin/webpack, --env.tnsAction, build, --env.android], rss=213778432, heapTotal=142598144, heapUsed=104980864, external=615883, loadavg=[0.279296875, 0.50341796875, 0.578125], uptime=8871, trace=[], stack=undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-vue@1.0.0 build: `webpack --env.tnsAction build "--env.android"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-vue@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/toyah/.npm/_logs/2018-05-24T08_42_20_655Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-vue@1.0.0 build:android: `npm run build -- --env.android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-vue@1.0.0 build:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/toyah/.npm/_logs/2018-05-24T08_42_20_713Z-debug.log

```

**Comment by socek** [comment]
For me, installing NativeScript helped:
https://docs.nativescript.org/start/quick-setup

**Comment by maganius** [comment]
I have the same error on windows 10:
 tns doctor says "No issues were detected."

```
info: Debugging NativeScript application...
Searching for devices...
error: uncaughtException: Command failed: node launch.js debug android
 date=Tue Jun 19 2018 08:55:51 GMT-0300 (Hora estándar de Montevideo), pid=8552, uid=null, gid=null, cwd=D:\Webs\opc, execPath=C:\Program Files\nodejs\node.exe, version=v8.9.1, argv=[C:\Program Files\nodejs\node.exe, D:\Webs\opc\node_modules\webpack\bin\webpack.js, --watch, --env.tnsAction, debug, --env.android], rss=181837824, heapTotal=158068736, heapUsed=102155816, external=1263414, loadavg=[0, 0, 0], uptime=734.5799625, trace=[column=12, file=child_process.js, function=ChildProcess.exithandler, line=275, method=exithandler, native=false, column=13, file=events.js, function=emitTwo, line=126, method=null, native=false, column=7, file=events.js, function=ChildProcess.emit, line=214, method=emit, native=false, column=16, file=internal/child_process.js, function=maybeClose, line=925, method=null, native=false, column=11, file=internal/child_process.js, function=Socket.stream.socket.on, line=346, method=on, native=false, column=13, file=events.js, function=emitOne, line=116, method=null, native=false, column=7, file=events.js, function=Socket.emit, line=211, method=emit, native=false, column=12, file=net.js, function=Pipe._handle.close [as _onclose], line=554, method=close [as _onclose], native=false], stack=[Error: Command failed: node launch.js debug android, ,     at ChildProcess.exithandler (child_process.js:275:12),     at emitTwo (events.js:126:13),     at ChildProcess.emit (events.js:214:7),     at maybeClose (internal/child_process.js:925:16),     at Socket.stream.socket.on (internal/child_process.js:346:11),     at emitOne (events.js:116:13),     at Socket.emit (events.js:211:7),     at Pipe._handle.close [as _onclose] (net.js:554:12)]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opc@1.0.0 debug: `webpack --watch --env.tnsAction debug "--env.android"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opc@1.0.0 debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Hansz\AppData\Roaming\npm-cache\_logs\2018-06-19T11_55_51_124Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opc@1.0.0 debug:android: `npm run debug -- --env.android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opc@1.0.0 debug:android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

UPDATE:

I fixed it!, the problem was the tns doesnt detect my device, I followed this comment and work correctly.

https://github.com/NativeScript/NativeScript/issues/4307#issuecomment-305855911

**Comment by HYordanov** [comment]
My device is detected but still I have that issue.. Could someone help fixing it or explain why we are experiencing it?

> error: uncaughtException: Command failed: node launch.js build android

**Comment by ThomCM** [comment]
Hi all,

I had this issue too. I found that if I tried building the app through Nativescript Sidekick it would throw the following error:

```
[18-07-16 09:55:11.291] Error detected during LiveSync on 988a5c385143314758 for C:\Users\Thomas\Documents\tns-apps\khrapp\template. Error: Command gradlew.bat failed with exit code 1 Error output: 
FAILURE: Build failed with an exception.
* What went wrong:
Unable to find a usable idle daemon. I have connected to 100 different daemons but I could not use any of them to run the build. BuildActionParameters were DefaultBuildActionParameters{, currentDir=C:\Users\Thomas\Documents\tns-apps\khrapp\template\platforms\android, systemProperties size=56, envVariables size=59, logLevel=QUIET, useDaemon=true, continuous=false, interactive=false, injectedPluginClasspath=[]}.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

After searching "Unable to find a usable idle daemon" I found this: https://stackoverflow.com/a/20479940

It says to **delete the .gradle file in the C:/Users/Thomas directory**.

I've now run it again through the cmd and it's successfully running on my android device.

My setup was just the vue-cli template and TNS doctor detected no issues. I had actually run it successfully before but I decided to delete the old installation and start fresh. I also cloned the ns-vue-firebase-test (https://github.com/EddyVerbruggen/ns-vue-firebase-test) template and run that successfully whilst the vue-cli template was failing.

**Comment by meddlin** [comment]
This seems obvious, but I hope this helps someone else.

I reached the original error because I attempted to setup NativeScript starting with the [NativeScript-Vue tutorial](https://www.nativescript.org/blog/setting-up-a-robust-nativescript-vue-development-environment) and completely overlooked the *actual* [NativeScript setup tutorial](https://www.nativescript.org/blog/setting-up-a-robust-nativescript-vue-development-environment).

https://www.nativescript.org/blog/setting-up-a-robust-nativescript-vue-development-environment
https://docs.nativescript.org/start/quick-setup
