### ISSUE TITLE
Xcode Issue

### ISSUE THREAD

**Issue by Laymono7** [nativescript-vue/vue-cli-template#56]
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✖ WARNING: Xcode is not installed or is not configured properly.

Hi Guys

I do have the issue  mentioned above, although I have xcode installed and I followed all the necessary steps as described here https://docs.nativescript.org/angular/tutorial/ng-chapter-1#11-creating-apps.

Please help

**Comment by rigoparis** [comment]
Hey @Laymono7!

You might want to follow this guide instead:

[https://docs.nativescript.org/start/ns-setup-os-x](https://docs.nativescript.org/start/ns-setup-os-x)

Hopefully it will get you up and running
