### ISSUE TITLE
Frame element won't compile on Android

### ISSUE THREAD

**Issue by elalienx** [nativescript-vue/vue-cli-template#60]
### Version
N/A

### Reproduction link
[https://github.com/elalienx/ns-vue-rc132v4-frame](https://github.com/elalienx/ns-vue-rc132v4-frame)
### Platform and OS info
NativeScript 4.0.1, NativeScript-Vue 1.3.2.v.4, tested emulator Android 6.0, developer computer Mac OS High Sierra 10.13.4.

### Steps to reproduce
1.- Download and install the NativeScript-Vue CLI Template from here: https://github.com/nativescript-vue/vue-cli-template
2.- Update the nativescript-vue from "^1.3.1" to "^1.3.2-rc.4" 
3.- Update the tns-core-modules from "~3.4.1" to "~4.1.0"
4.- Run npm install to update dependencies.
6.- Add a Frame as the main wrapper on the template in the HelloWorld.vue file.
7.- Run npm run watch:ios to confirm that it works.
8.- Run npm run watch:android and it won't work and throws the error "A frame must be used to navigate to a Page."

### What is expected?
To be able to use the Frame element to make complex navigation posible. Like the original NativeScript tab navigation sample: https://market.nativescript.org/plugins/tns-template-tab-navigation

### What is actually happening?
1.- On iOS works fine. You can use the Frame element to make a single page or a tab navigation.
2.- On Android you can't make a single page using Frame because it throws an error saying "A frame must be used to navigate to a Page." Even when you are using a Frame.

---
I ran into this bug when a created a new branch on a project that required a Tab navigation like the Nativescript tab navigation template where the tabs are always present, and where you can navigate to sub pages from each tab.

**Comment by rigor789** [comment]
Please give `1.4.0-alpha.0` a try for the `Frame` element, Check https://github.com/nativescript-vue/nativescript-vue/issues/239#issuecomment-394780299 for instructions for updating, you need to add an options object to `$start`.
