### ISSUE TITLE
Upgrade nativescript

### ISSUE THREAD

**Issue by xeroxstar** [nativescript-vue/vue-cli-template#65]
Hello, i am trying to update nativescript by running tns update and it looks like it's updating:

`c:\myproject-vue-tns\ tns update`

but after i run tns --version i get the same version as it was before an update. 
`c:\myproject-vue-tns\ tns --version`
I also tried to update:
`c:\myproject-vue-tns\app\ tns update`
and it didn't work.

How do i update the nativescript with vue template?

thx

**Comment by arzke** [comment]
To update nativescript, you have to update tns-core-modules to desired version with npm/yarn.
