### ISSUE TITLE
registerBroadcastReceiver doesn't work

### ISSUE THREAD

**Issue by krvd** [nativescript-vue/vue-cli-template#66]
### Version
N/A

### Reproduction link
[https://github.com/krvd/nativescript-vue-cli-example](https://github.com/krvd/nativescript-vue-cli-example)
### Platform and OS info
android 7.0 / {N} 4.1.2 / windows 10, 

### Steps to reproduce
register broadcast receiver

### What is expected?
correctly register brodcast receiver

### What is actually happening?
Broadcast receivers are pushed into application.android._pendingReceiverRegistration and never register properly. Even after running Vue().$start()

**Comment by absolutehype** [comment]
The `init` method doesn't seem to get fired so the receivers don't register

https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/application/application.android.ts#L55

**Comment by krvd** [comment]
Yes but i dont understand why. It seems like something overrides nativescript-vue `$start` or `$mount` methods. Maybe its one of vue plugins which are the part of nativescript-vue?

**Comment by absolutehype** [comment]
@krvd i've not had time to properly investigate this, however, this worked as a temporary solution for me.

```js
import Vue from 'nativescript-vue';
import * as app from 'tns-core-modules/application';

import App from './App';

new Vue({
    render: h => h(App),
    store
}).$start({
    getRootView(vm) {
        return vm.$el.nativeView
    }
});

app.start();
```

**Comment by krvd** [comment]
It looks like a bug. But thank you for your solution!
