### ISSUE TITLE
npm run watch:android not working - Windows 10

### ISSUE THREAD

**Issue by aonix-group** [nativescript-vue/vue-cli-template#69]
// Instalated using docs steps

npm install -g @vue/cli @vue/cli-init
vue init nativescript-vue/vue-cli-template <project-name>
cd <project-name>
npm install
npm run watch:android

// Return

info: Bundling application for android...

Webpack is watching the files…

Executing post-build scripts
info: Running NativeScript application...
Searching for devices...
Starting Android emulator with image Nexus_4_API_24
Waiting for emulator device initialization...
Copying template files...

**Unable to apply changes on device: emulator-5554. Error is: Command failed: npm view tns-android  dist-tags --json**

npm WARN invalid config access=undefined                              
npm WARN invalid config also=undefined                                
npm WARN invalid config https-proxy=undefined                         
npm WARN invalid config Must be a full url with 'http://'             
npm WARN invalid config init-author-url=undefined                     
npm WARN invalid config Must be a full url with 'http://'             
npm WARN invalid config only=undefined                                
npm WARN invalid config proxy=undefined                               
npm WARN invalid config Must be a full url with 'http://'             
npm WARN onload-script failed to require onload script undefined      
npm WARN onload-script Error: Cannot find module 'undefined'          
npm WARN onload-script     at Function.Module._resolveFilename (module
npm WARN onload-script     at Function.Module._load (module.js:466:25)
npm WARN onload-script     at Module.require (module.js:579:17)       
npm WARN onload-script     at require (internal/module.js:11:18)      

npm WARN onload-script  { Error: Cannot find module 'undefined'
npm WARN onload-script     at Function.Module._resolveFilename (module.js:536:15)
npm WARN onload-script     at Function.Module._load (module.js:466:25)
npm WARN onload-script     at Module.require (module.js:579:17)
npm WARN onload-script     at require (internal/module.js:11:18)

npm WARN onload-script   stack: 'Error: Cannot find module \'undefined\'\n    at Function.Module._resolveFilename (module.js:536:15)\n    at Function.Module._load (module.js:466:25)\n    at Module.require (module.js:579:17)\n    at require (internal/module.js:11:18)\n    at cb ...

npm WARN onload-script   code: 'MODULE_NOT_FOUND' }
npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line

**I'm verify tns doctor and:
No issues were detected.

And i'm did all steps from:
https://docs.nativescript.org/start/quick-setup#step-3-install-ios-and-android-requirements

Ambient environment works fine on nativescript-vue/nativescript-vue-template, phonegap and android studio

I removed last AVD and create a new AVD, problem continues**

**Comment by rigor789** [comment]
Looks like an NPM issue
> `npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line`

See https://github.com/npm/npm/issues/10897#issuecomment-167396880
