### ISSUE TITLE
Changing the application name

### ISSUE THREAD

**Issue by rigoparis** [nativescript-vue/vue-cli-template#7]
Hey!

First of all, thanks for this repo and for all the work you've done.

Now, I've been experimenting with your approach to NativeScript-Vue and I've stumbled upon the next issue: 

I can't change the name of the application. I've tried changing the name with NativeScript Sidekick but it's grayed out with 'template' and I'm unable to change it. I've also tried changing the `android:label` inside the `AndroidManifest.xml` on the template folder and `CFBundleDisplayName` inside `Info.plist` for iOS. When the aplication asks for permission to install, the correct name is shown. However, when the app is minimized the name below the icon remains as `dist`.

Is there anything I'm missing? Can you maybe guide me on the right track?

Thanks again for everything and I'll eagerly wait for your response.

**Comment by lewebsimple** [comment]
Have you tried the latest 0.2.0 branch? The app name is set for Android (via App_Resources/Android/values-v21/strings.xml), I'll try to get iOS to do the same very soon.
Actually, I think of having a seperate prompt for this as there are restrictions on the app id vs app name vs app title. The goal being able to set the "human readable" app name when scaffolding the app from `vue init`.
Edit:
To try the 0.2.0 branch:
```
vue init nativescript-vue/vue-cli-template#0.2.0 projectname
```

**Comment by rigoparis** [comment]
Thanks dude! I'll give it a go and I'll bother you back if anything. Thanks again!
