### ISSUE TITLE
[iOS] JS ERROR SyntaxError: Unexpected token '...'. Expected a property name.

### ISSUE THREAD

**Issue by odai-alali** [nativescript-vue/vue-cli-template#77]
on **iPhone 6 Emulator / Nativescript 4.2.0 / MacOS 10.13.6** using spread operator `...` is not supported.
tried to install `transform-object-rest-spread` as dev dependency (already added in .babelrc) without success.

It works on android without problems!

**Comment by jlooper** [comment]
I believe @tralves added spread operator support for iOS in the #next branch.

**Comment by dmsmidt** [comment]
I can confirm this bug has been fixed in #82 on the 'next' branch.
