### ISSUE TITLE
Working with Plugins

### ISSUE THREAD

**Issue by aaronksaunders** [nativescript-vue/vue-cli-template#8]
Trying to test out the camera plugin and I found that following the documentation

```
import { Image } from "ui/image";
```
doesnt work...
```
error : JS ERROR Error: Could not find module './image-common'. Computed path '/Users/aaronsaunders/Library/Developer/CoreSimulator/Devices/A5263510-03D1-4596-A2E4-3E998D534310/data/Containers/Bundle/Application/D7E9BE61-5F1F-4AB3-AEF9-26653AEC1FCA/dist.app/app/image-common'.
```
you have to actually specify the specific path for the module including the `tns-core-modules`.. So this works; Is this the expected behavior
```
import { Image } from "tns-core-modules/ui/image";
```

**Comment by brunokunace** [comment]
I try to use camera plugin too, but dont work. (i dont know how to best way to install it)

i make this:
1) npm install nativescript-camera --save (on root directory) **
2) import camera from nativescript-camera module ***
3) requestPermissions() on mounted, only for test. 

attachs:
** package.json https://gist.github.com/brunokunace/bd2476e52daebcd07cc4b555a37f01a7
*** App.vue https://gist.github.com/brunokunace/fda6e351940593013b65bfbd88a1944b


ERROR:
```
Successfully transferred app.css.
Refreshing application...
Successfully synced application org.nativescript.application on device d69097630204.
ActivityManager: Start proc 19772:org.nativescript.application/u0a170 for activity org.nativescript.application/com.tns.NativeScriptActivity caller=null
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException:
System.err:
System.err: Error calling module function
System.err:
System.err: Error: com.tns.NativeScriptException: Failed to find module: "./application-common", relative to: app/
```

**Comment by lewebsimple** [comment]
Please use `import { Image } from "tns-core-modules/ui/image";`

**Comment by brunokunace** [comment]
install plugin using tns cli work only on template folder, but webpack does not locate the plugin, i try very times, but i dont make it works.
Please Help!

**Comment by lewebsimple** [comment]
@brunokunace Install in the project folder using `npm install nativescript-myplugin`

**Comment by brunokunace** [comment]
@lewebsimple thanks for answer, but i try it.

Receive this error on console:

`System.err: Error: com.tns.NativeScriptException: Failed to find module: "./application-common", relative to: app/`

my App.vue example
https://gist.github.com/brunokunace/12ffe9d91ee527d019f09452e5e14641

my package.json on root
https://gist.github.com/brunokunace/7aea3edfcb327d6a81158077d5205bb7

**Comment by brunokunace** [comment]
anything about it?
(i a newbie on nativescript, maybe this error is mine, please teste)

**Comment by aaronksaunders** [comment]
@brunokunace  modify your code to import the library like this...
```
import * as Toast from "nativescript-toast";
```
also which template did you use to create your project?

**Comment by lewebsimple** [comment]
@brunokunace can you post your `webpack.config.js` file? Make sure `externals` is set to resolve plugins externally. you can use `const externals = require('nativescript-vue-externals')` for this like in the 0.2.0 branch

**Comment by brunokunace** [comment]
@aaronksaunders thanks for answer, but it dont make change (i use import too)

@lewebsimple you Great! external it was the problem, i try use from master branch and plugins dont working, with branch 0.2.0 works fine.

Note: branch 0.2.0 is awesome, console more verbose to call actions to build, styling on cli init, beautifull work!

please, if no have anymore with @aaronksaunders, close this issue.

**Comment by gle6as** [comment]
First of all, thanks for the awesome template!
But how I can install plugin like google maps with native components?
Should I install it in template folder with tns plugin add nativescript-google-maps-sdk?

**Comment by lewebsimple** [comment]
I've updated the documentation regarding this, please refer to https://github.com/nativescript-vue/vue-cli-template/tree/0.2.0#using-nativescript-plugins

**Comment by gle6as** [comment]
Thanks, got it.
But still can't make maps work.
As for now I have this error when building:
`JS ERROR Error: Could not find module './map-view-common'. Computed path '/var/mobile/Containers/Data/Application/17DFF359-BFD3-475B-81C4-B1F18699B1C1/Library/Application Support/LiveSync/app/map-view-common'.`

I tried to do `import * as maps from 'nativescript-google-maps-sdk'` and `require('nativescript-google-maps-sdk')`

As I see webpack can't resolve some internal modules for maps. May be we need to add some resolve options in webpack config?

**Comment by rigoparis** [comment]
EDIT: Changed the error log, the one I originally posted was an irrelevant one
EDIT2: Included the link to the plugin from the error message.

Hey @lewebsimple!

I've been having the same issues as @gle6as. I've noticed this happens with plugins that have not been migrated to {N}3. I've tried several plugins that have been migrated, for example, the Camera and  ImagePicker and they do work. However when I try to install any other plugin that is not migrated I get the same error. 

I've tried to migrate plugins using the [https://github.com/NativeScript/NativeScript/wiki/Migrating-Plugins-to-NativeScript-3.0](url) guide with no results.

Are you able to run 3rd party plugins that may have not been migrated to {N}3?

I'm running {N} 3.4.3 on Node v8.9.4 with Vue 2.9.3 
If you need any other piece of information I am more than glad to provide it.

Plugin on test: `"nativescript-ui-sidedrawer": "3.5.0"`
[https://www.npmjs.com/package/nativescript-ui-sidedrawer](url)
And on most plugins I get this error:

```
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
System.err: Error calling module function 
System.err: Error: com.tns.NativeScriptException: Failed to find module: "./ui-sidedrawer.common", relative to: app/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:530)
System.err:     com.tns.Runtime.run(Runtime.java:522)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4793)
System.err:     android.app.ActivityThread.access$1900(ActivityThread.java:152)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:135)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5538)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:372)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace: 
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 191000
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 182246
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'Object.defineProperty.value', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 177624
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'Object.defineProperty.value', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 176906
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'Object.defineProperty.value', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 149872
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 147779
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 511
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 521
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: Error: com.tns.NativeScriptException: Failed to find module: "./ui-sidedrawer.common", relative to: app/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:530)
System.err:     com.tns.Runtime.run(Runtime.java:522)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4793)
System.err:     android.app.ActivityThread.access$1900(ActivityThread.java:152)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:135)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5538)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:372)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace: 
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 191000
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 182246
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'Object.defineProperty.value', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 177624
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'Object.defineProperty.value', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 176906
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'Object.defineProperty.value', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 149872
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 147779
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 511
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 521
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4802)
System.err: 	at android.app.ActivityThread.access$1900(ActivityThread.java:152)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:135)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5538)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Error calling module function 
System.err: Error: com.tns.NativeScriptException: Failed to find module: "./ui-sidedrawer.common", relative to: app/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:530)
System.err:     com.tns.Runtime.run(Runtime.java:522)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4793)
System.err:     android.app.ActivityThread.access$1900(ActivityThread.java:152)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:135)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5538)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:372)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace: 
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 191000
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 182246
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'Object.defineProperty.value', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 177624
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'Object.defineProperty.value', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 176906
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'Object.defineProperty.value', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 149872
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 147779
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 511
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 521
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: Error: com.tns.NativeScriptException: Failed to find module: "./ui-sidedrawer.common", relative to: app/
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:530)
System.err:     com.tns.Runtime.run(Runtime.java:522)
System.err:     com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:4793)
System.err:     android.app.ActivityThread.access$1900(ActivityThread.java:152)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1402)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:135)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5538)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:372)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace: 
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 191000
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 182246
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'Object.defineProperty.value', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 177624
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'Object.defineProperty.value', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 176906
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'Object.defineProperty.value', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 149872
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 147779
System.err: 	Frame: function:'t', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 161
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 511
System.err: 	Frame: function:'', file:'file:///data/data/com.ciriscr.movil/files/app/app.js', line: 1, column: 521
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	at com.tns.Runtime.runModule(Native Method)
System.err: 	at com.tns.Runtime.runModule(Runtime.java:530)
System.err: 	at com.tns.Runtime.run(Runtime.java:522)
System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4793)
System.err: 	... 9 more
```

**Comment by rigor789** [comment]
If it happens to plugins that are not migrated to {N}3 then there is nothing we can really do about that (other than updating the plugin, and submitting a PR). I'm assuming these plugins fail to run even in pure js {N}.

**Comment by rigoparis** [comment]
@rigor789 I understand, thanks just wanted to see if there was any other solution than using an older version of {N}. And can I ask what version of {N} are you using or recommend using?

**Comment by rigor789** [comment]
I'm using 3.4.1 (latest) and I strongly recommend sticking to the latest release, because there are quite large performance improvements compared to let's say 2.5. You may be able to find updated versions of the plugins that you are looking for, but if not, you can attempt to update them, in most cases I don't think there are many changes required granted, my limited experience with plugins.

**Comment by rigoparis** [comment]
Understood, thanks again for the support and the great work. You can close this now :)

**Comment by gle6as** [comment]
Thanks for suggestions, but as I know, `nativescript-googlemaps` and newer version `nativescript-google-maps-sdk` already migrated to N3.

**Comment by Informateur** [comment]
The same error as @gle6as . I'm trying to add nativescript-geolocation. It works fine on vanilla {N} 3, but not here.

**Comment by lewebsimple** [comment]
Please try again with nativescript-vue-externals 0.1.1 (and do npm run clean)

**Comment by gle6as** [comment]
Now I got this error:
`JS ERROR TypeError: undefined is not an object (evaluating 'b.prototype')`

**Comment by gle6as** [comment]
Tested with `nativescript-geolocation ` and it works fine.
Maybe the problem happens only with google-maps package?

UPD: looks like references to `tns-core-modules` inside maps package can't resolve properly

**Comment by Informateur** [comment]
Now all my plugins are working. Thank you.
Still to Windows deploy, would pass to this assembly. Encouraging.

**Comment by gle6as** [comment]
Hey guys, I still have issues with some plugins.
As I can see the problem in .ts files.
For example `nativescript-maskedinput`

I have this error
`ERROR in ./src/main.js
Module not found: Error: Can't resolve 'nativescript-maskedinput' in '/Users/gleb/Dev/mashinka/Mashinka/src'
 @ ./src/main.js 29:18-53
 @ multi babel-polyfill ./src/main.js`

I logged context and request in `NativeScriptVueExternals` and it shows that requests identical for this plugin and mapbox, which is working fine.
`/Users/gleb/Dev/mashinka/Mashinka/src
nativescript-maskedinput
/Users/gleb/Dev/mashinka/Mashinka/src
nativescript-mapbox`

BTW, my webpack config:
`const path = require('path');
const webpack = require('webpack');
const winston = require('winston-color');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const WebpackSynchronizableShellPlugin = require('webpack-synchronizable-shell-plugin');
// const NativeScriptVueExternals = require('nativescript-vue-externals');
const NativeScriptVueTarget = require('nativescript-vue-target');
const babelPolyfill = require('babel-polyfill')

const NativeScriptVueExternals = (context, request, callback) => {

	console.log(context)
	console.log(request)

	if (context.indexOf('tns-core-modules') !== -1 ||
		context.indexOf('nativescript-') !== -1 ||
		/^(tns-core-modules)/i.test(request)) {

		if (request.indexOf("./") === 0) {
			request = path.join(path.basename(context), request.substring(2))
		}
		return callback(null, 'commonjs ' + request)

	}
	callback();
}




// Prepare NativeScript application from template (if necessary)
require('./prepare')();

// Generate platform-specific webpack configuration
const config = (platform, launchArgs) => {

	winston.info(`Bundling application for ${platform}...`);

	// CSS / SCSS style extraction loaders
	const cssLoader = ExtractTextPlugin.extract({
		use: [{
			loader: 'css-loader',
			options: {
				url: false
			},
		}, ],
	});
	const scssLoader = ExtractTextPlugin.extract({
		use: [{
				loader: 'css-loader',
				options: {
					url: false,
					includePaths: [path.resolve(__dirname, 'node_modules')],
				},
			},
			'sass-loader',
		],
	});

	return {

		target: NativeScriptVueTarget,

		entry: ['babel-polyfill', path.resolve(__dirname, './src/main.js')],

		output: {
			path: path.resolve(__dirname, './dist/app'),
			filename: `app.${platform}.js`,
		},

		module: {
			rules: [{
					test: /\.js$/,
					exclude: /(node_modules)/,
					loader: 'babel-loader',
				},
				{
					test: /\.css$/,
					use: cssLoader,
				},
				{
					test: /\.scss$/,
					use: scssLoader,
				},

				{
					test: /\.vue$/,
					loader: 'ns-vue-loader',
					options: {
						loaders: {
							css: cssLoader,
							scss: scssLoader,
						},
					},
				},
			],
		},

		resolve: {
			modules: [
				'node_modules/tns-core-modules',
				'node_modules',
				'node_modules/*',
			],
			extensions: [
				`.${platform}.css`,
				'.css',
				`.${platform}.scss`,
				'.scss',
				`.${platform}.js`,
				'.js',
				`.${platform}.vue`,
				'.vue',
				'.ts',
				'.tsx',
			],
			alias: {
				'@': path.resolve(__dirname, './src'),
			}
		},

		externals: NativeScriptVueExternals,

		plugins: [

			// Extract CSS to separate file
			new ExtractTextPlugin({
				filename: `app.${platform}.css`
			}),

			// Optimize CSS output
			new OptimizeCssAssetsPlugin({
				cssProcessor: require('cssnano'),
				cssProcessorOptions: {
					discardComments: {
						removeAll: true
					}
				},
				canPrint: false,
			}),

			// Minify JavaScript code
			new webpack.optimize.UglifyJsPlugin({
				compress: {
					warnings: false
				},
				output: {
					comments: false
				},
			}),

			// Copy src/assets/**/* to dist/
			new CopyWebpackPlugin([{
				from: 'assets',
				context: 'src'
			}, ]),

			// Execute post-build scripts with specific arguments
			new WebpackSynchronizableShellPlugin({
				onBuildEnd: {
					scripts: [
						...launchArgs ? [`node launch.js ${launchArgs}`] : [],
					],
					blocking: false,
				},
			}),

		],

		stats: 'errors-only',

		node: {
			'http': false,
			'timers': false,
			'setImmediate': false,
			'fs': 'empty',
		},

	};
};

// Determine platform(s) and action from webpack env arguments
module.exports = env => {
	const action = (!env || !env.tnsAction) ? 'build' : env.tnsAction;

	if (!env || (!env.android && !env.ios)) {
		return [config('android'), config('ios', action)];
	}

	return env.android && config('android', `${action} android`) ||
		env.ios && config('ios', `${action} ios`) ||
		{};
};
`

And bablerc
`{
	"presets": [
		["env", {
			"cacheDirectory": true
		}],
		"es2015",
		"stage-0"
	],
	"plugins": ["transform-object-rest-spread"]
}
`
Any ideas?
