### ISSUE TITLE
Error in reading bitmap 

### ISSUE THREAD

**Issue by jaasaria** [nativescript-vue/vue-cli-template#84]
### Version
N/A

### Reproduction link
[https://github.com/nativescript-vue/vue-cli-template](https://github.com/nativescript-vue/vue-cli-template)
### Platform and OS info
Android API26, NS: 4.2.3, Win10 64x

### Steps to reproduce
(Following the steps on how to install NS-Vue template via https://nativescript-vue.org/en/docs/getting-started/templates)

After installing all dependencies  and run the final command "tns run android --bundle",
Cli compile and run the application on my AVD. All is working except that Im having a error logs saying: 

"JS: Error in reading bitmap - java.io.FileNotFoundException: /data/data/org.nativescript.application/files/app/images/NativeScript-Vue.png (No such file or directory)"

Also I notice that in my emulator under "Counter Component", when counter reach >=5, the NativeScript-Vue.png  dont show up.

### What is expected?
I expect clean CLI(for better debugging) and the "NativeScript-Vue.png" should show up after condition is set true.

### What is actually happening?
Under CLI the error keeps popping up.
NativeScript-Vue.png  not showing up under counter component

PS: HellowWorld component working fine

---
Ill add also what I notice in my cli that node_modules being skiped.
Attach the screenshot for further reference .

https://ibb.co/mQV3c9
https://ibb.co/fLfx4p

**Comment by rigor789** [comment]
Thanks for opening the issue, I found the problem! We have just updated the template, and looks like we forgot to update the image path in the Counter component.

To fix it, go into Counter.vue and change the following line
```xml
 <Image v-if="surprise" src="~/images/NativeScript-Vue.png"/>
```
to 
```xml
 <Image v-if="surprise" src="~/assets/images/NativeScript-Vue.png"/>
```

Fixed in the template as well.
