### ISSUE TITLE
Fresh project importing problem

### ISSUE THREAD

**Issue by maxflex** [nativescript-vue/vue-cli-template#86]
### Version
npm 5.6
node 9.9
vue 3.0.3
### Platform and OS info
MacOS 10.13.3

### Steps to reproduce
`tns run ios` or `tns debug ios` on fresh project

### What is actually happening?
Could not find module './components/Counter'

---

Can't get a fresh project to run. 

> Could not find module './components/Counter'`. 

Generally it doesn't import anything from the `app` folder.

Furthermore, if I comment out the `import Counter from './components/Counter';` line, then I get another error from `styles.scss`, 

> app/styles.scss:3: JS ERROR SyntaxError: Invalid character: '@'

Which resembles [this closed issue](https://github.com/nativescript-vue/vue-cli-template/issues/21) though my project doesn't have `nativescript` in its name.

**Comment by jiraiya972** [comment]
you need to use --bundle option when you run tns. `tns run ios --bundle`

cf https://nativescript-vue.org/en/docs/getting-started/quick-start/

**Comment by maxflex** [comment]
@jiraiya972 thanks, `--bundle` seems to have solved it! But the problem progresses further and now I'm getting this:

> file:///app/bundle.js:352:130: JS ERROR Error: Cannot find module './styles.scss'

This is after I run `tns run ios --bundle` on a completely fresh instalment

**Comment by ngstwr** [comment]
Might be related to this https://github.com/NativeScript/nativescript-dev-webpack/issues/665

**Comment by brobee** [comment]
I am unable to use preview (playground app) because it's crashing. Why am I unable to run the demo app without --bundle? Any solution?

**Comment by rigor789** [comment]
Closing as outdated.
