### ISSUE TITLE
Fresh build problem on linux

### ISSUE THREAD

**Issue by rimonmath** [nativescript-vue/vue-cli-template#88]
### Version
N/A

### Reproduction link
[https://github.com/nativescript-vue/vue-cli-template](https://github.com/nativescript-vue/vue-cli-template)
### Platform and OS info
Xubuntu 18.04

### Steps to reproduce
1. Create project as git documentation. 
2. cd project-name
3. npm install
4. tns run android --bundle

### What is expected?
Run fresh project without any error

### What is actually happening?
Running the project with error. The error message is like :

ERROR in ./router/index.js Module not found: Error: Can't resolve '../components/Counter'

---
This error happens for all the components HelloWorld.vue, Counter.vue and Home.vue. 
If i write the code with .vue extension like 

import Counter from '../components/Counter.vue';

Then another error occurred. It shows error for template tag. Seems vue-loader not configured currectly

**Comment by rigor789** [comment]
This may have to do with the broken release we had yesterday. Can you try again with the latest release (2.0.0-rc.0) and let us know if it works for you?

**Comment by rimonmath** [comment]
how can I get the code of (2.0.0-rc.0)?

**Comment by rigor789** [comment]
`npm install` should update the package, but if it still uses the old one, change the `package.json` to use `"nativescript-vue": "2.0.0-rc.0"`

**Comment by rimonmath** [comment]
Thanks!

**Comment by rigor789** [comment]
@rimonmath  Is the issue solved?

**Comment by rimonmath** [comment]
@rigor789  Nope. currently having other problems. main.js file contains error. single quotation is missing on line 3. If I fix it manually, then other error occurs. class not found exception: java.lang.Class.ClassForName.

**Comment by rigor789** [comment]
What's on line 3? Also can you include the output for the ` java.lang.Class.ClassForName` exception?

**Comment by rimonmath** [comment]
line three is as follow:
import './styles.scss

It should be:
import './styles.scss'

**Comment by rigor789** [comment]
Okay, that was also a mistake on our part - fixed in #97 🙄 

How about the `java.lang.Class.ClassForName` exception?
