### ISSUE TITLE
npm run watch not working (Windows 10)

### ISSUE THREAD

**Issue by Informateur** [nativescript-vue/vue-cli-template#9]
When I try to run on android, the process stumbles. Similarly, npm run build.
What logs the console:

...
info: Running NativeScript application...
Searching for devices...
Copying template files...
Installing tns-android
Unable to apply changes on device: 1ed1de2f9804. Error is: Command failed: npm view tns-android  dist-tags --json
...

Tried under Mac OS from a friend, both platforms run well. 
How can I make it work in Windows?

**Comment by lewebsimple** [comment]
Please refer to the official NativeScript documentation and make sure your environment is properly configured: 
https://docs.nativescript.org/start/quick-setup#step-3-install-ios-and-android-requirements

**Comment by Informateur** [comment]
Vanilla {N} 3 works well.
tns doctor - no problem
