### ISSUE TITLE
RadSideDrawer not working on fresh install

### ISSUE THREAD

**Issue by DevPlus31** [nativescript-vue/vue-cli-template#95]
### Version
N/A

### Reproduction link
[https://github.com/nativescript-vue/vue-cli-template](https://github.com/nativescript-vue/vue-cli-template)
### Platform and OS info
Windows 10, NativeScript Vue 2.0.0

### Steps to reproduce
install Vue-Cli-template 
Select RadSideDrawer layout 
build, run 

### What is expected?
Usable application

### What is actually happening?
Crash at the loading 
with (No known component for element RadSideDrawer) 

---
I added Vue.registerElement('RadSideDrawer', () => require('nativescript-ui-sidedrawer').RadSideDrawer); to the main file but without success.

**Comment by rigor789** [comment]
Fixed in #96
